### ISSUE TITLE
添加Header卡顿问题

### ISSUE THREAD

**Issue by KKJJ** [jdsjlzx/LRecyclerView#1]
添加了ViewPager作为头部，上滑一小段至头部刚好不可见，然后用手指按住向下拖动，在经过头部时会卡住

**Comment by jdsjlzx** [comment]
有没有截图？我看不到你的效果！是用的最新代码吗？7.23刚更新和优化了代码。

**Comment by KKJJ** [comment]
嗯，看到刚更新，不过不是用的最新的，之前就接进来了，因为公司wifi有问题暂时不方便截图，我试着添加两个header，但是在header和列表之间下滑的时候就是会卡住，新版本在这方面有修复？？

**Comment by jdsjlzx** [comment]
你用最新的demo试一下，我暂时还没有发现你说的问题。新版本如果还有问题，及时提出。

**Comment by KKJJ** [comment]
好的，我试试，谢谢

**Comment by KKJJ** [comment]
好的，我试试，谢谢

**Comment by KKJJ** [comment]
替换为新版  没有卡顿问题了  再次THX
