### ISSUE TITLE
代码疏忽

### ISSUE THREAD

**Issue by Fisherman91** [jdsjlzx/LRecyclerView#102]
你好，最近在研习你的代码，这里应该是个疏漏吧？这样岂不是每次设置loading状态时都会添加一个progress view？
![image](https://cloud.githubusercontent.com/assets/17759213/22096678/e3c93a36-de57-11e6-9aef-98f2759d6cc1.png)

**Comment by jdsjlzx** [comment]
你好，确实疏忽了，应该先removeAllViews。

mProgressView.removeAllViews();
mProgressView.addView(initIndicatorView(style));

感谢你的反馈！
