### ISSUE TITLE
Observer com.github.jdsjlzx.recyclerview.LRecyclerView$DataObserver@e0761ae was not registered.

### ISSUE THREAD

**Issue by BlackJia** [jdsjlzx/LRecyclerView#103]

**Comment by BlackJia** [comment]
Adapter a = new Adapter;
mLRecyclerViewAdapter = new LRecyclerViewAdapter(a);
list.setAdapter(mLRecyclerViewAdapter);

第一遍初始化没有问题，(刷新，实在懒得做判断了就直接又来了一遍)第二遍同样这样设置就报这个错误了。
我暂时把 那个setAdapter()中的if(flag)注释掉了，应该是我使用姿势不正确。

**Comment by jdsjlzx** [comment]
list.setAdapter(mLRecyclerViewAdapter);调用一次就可以了，不要多次setAdapter，初始化后，需要更新就使用mLRecyclerViewAdapter.notifyDataSetChanged();
