### ISSUE TITLE
添加依赖运行报错

### ISSUE THREAD

**Issue by jasonfresher** [jdsjlzx/LRecyclerView#104]
你好，按照wiki中的步骤添加依赖

Step 1. 在你的根build.gradle文件中增加JitPack仓库依赖。
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

Step 2. 在你的model的build.gradle文件中增加LRecyclerView依赖。
compile 'com.github.jdsjlzx:LRecyclerView:1.3.3'

运行项目直接报错：Binary XML file line #8: Error inflating class com.github.jdsjlzx.recyclerview.LRecyclerView，请问是什么原因呢？

**Comment by jdsjlzx** [comment]
添加依赖出的问题，可以参考：https://github.com/jdsjlzx/Community_RxJava2

**Comment by jasonfresher** [comment]
解决了，由于两个包冲突原因
