### ISSUE TITLE
你好，请问最新代码中的SwipeMenuView和SwipeMenuLayout项目中找不到

### ISSUE THREAD

**Issue by loulijun** [jdsjlzx/LRecyclerView#105]
最新代码中SwipeMenuView和SwipeMenuLayout两个文件找不到，看xml中是在com.github.jdsjlzx.swipe中，但是这个目录是不存在的，能否提供下这两个文件源码？

**Comment by jdsjlzx** [comment]
参考：https://github.com/yanzhenjie/SwipeRecyclerView

SwipeRecyclerView滑动的时候有点卡，希望你能注意这个问题！正是这个原因我才不用这个库了！
