### ISSUE TITLE
刷新数据问题

### ISSUE THREAD

**Issue by ADL1121** [jdsjlzx/LRecyclerView#106]
加载更多时，调用mLRecyclerViewAdapter.notifyDataSetChanged()列表图片（已加载的）会闪烁。

**Comment by jdsjlzx** [comment]
尝试下：
mDataAdapter.notifyDataSetChanged()；（mDataAdapter为你自己本地的adapter）
如果不行，你就用下面的api试下：
public final void notifyItemRangeChanged(int positionStart, int itemCount, Object payload) {
            mObservable.notifyItemRangeChanged(positionStart, itemCount, payload);
 }

**Comment by jdsjlzx** [comment]
我暂时关闭该issue，如有问题，请再提问！
