### ISSUE TITLE
反馈BUG，setSpanSizeLookup下标越界，

### ISSUE THREAD

**Issue by 50kg** [jdsjlzx/LRecyclerView#108]
SwipeRefreshLayout嵌套LuRecyclerView，网格布局，在使用setSpanSizeLookup方式，position下标会越界，替换成官方RecyclerView则没有问题。

**Comment by 50kg** [comment]
补充，当数据有10条时，滑动加载理论position为0~9。LuRecyclerView会多一个，0~10造成下标越界

**Comment by jdsjlzx** [comment]
贴一下你的代码吧

**Comment by 50kg** [comment]
我结合drakeet/Effective-MultiType的库使用
`items = new Items();
                    List<LiveBean.DataBean.PartitionsBean> partitions = liveBean.getData().getPartitions();
                    for (int i = 0; i < partitions.size(); i++) {
                        LiveBean.DataBean.PartitionsBean.PartitionBean partition = partitions.get(i).getPartition(i);
                        items.add(partition);
                        for (int j = 0; j < 4; j++) {
                            LiveBean.DataBean.PartitionsBean.LivesBean livesBean = partitions.get(i).getLives().get(j);
                            items.add(livesBean);
                        }
                    }

mLuRecyclerViewAdapter = new LuRecyclerViewAdapter(adapter);

                    GridLayoutManager manager = new GridLayoutManager(getActivity(), 2);

                    /* 关键内容：通过 setSpanSizeLookup 来告诉布局，你的 item 占几个横向单位，
                    如果你横向有 5 个单位，而你返回当前 item 占用 5 个单位，那么它就会看起来单独占用一行 */

                    manager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
                        @Override
                        public int getSpanSize(int position) {

                            Object item = items.get(position);
                            Log.d("TAG", "getSpanSize: " + position);

                            if (item instanceof LiveBean.DataBean.PartitionsBean.PartitionBean) {
                                return 2;
                            } else {
                                return 1;
                            }
                        }
                    });

                    recyclerView.setAdapter(mLuRecyclerViewAdapter);
                    recyclerView.setLayoutManager(manager);`

**Comment by 50kg** [comment]
item是数据的总条数，下面循环出数据，然后根据不同的数据进行网格宽度设置。
假如我总数据是20，那么getSpanSize position应该是0~19，我用RecyclerView则不报异常，替换成Lu则0~20

**Comment by jdsjlzx** [comment]
参考demo中的MulItemGridLayoutActivity、BilibiliActivity类的实现。

**Comment by jdsjlzx** [comment]
如果没有问题，我先关闭该issue，如有问题你可以重新提issue！

**Comment by 50kg** [comment]
好的，thk
