### ISSUE TITLE
In ReadMe, the second onScrolldown should be on Scrolled

### ISSUE THREAD

**Issue by oldwang66** [jdsjlzx/LRecyclerView#11]

**Comment by jdsjlzx** [comment]
onScrolled区分不了是向上滑动还是向下滑动。如下所示，基本上滑动事件很全面了。
void onScrollUp();//scroll down to up
void onScrollDown();//scroll from up to down
void onScrolled(int distanceX, int distanceY);// moving state,you can get the move distance
