### ISSUE TITLE
为了解决图片闪烁使用了setHasStableIds后导致的问题

### ISSUE THREAD

**Issue by GavinAndre** [jdsjlzx/LRecyclerView#110]
我想解决刷新图片闪烁的问题，因此在adapter里使用设置tag的方式保存信息
```
viewHolder.mPreview.setTag(item.getScaledUrl());
```
然后分别为mDataAdapter和mLRecyclerViewAdapter开启了setHasStableIds
```
mDataAdapter.setHasStableIds(true);
mLRecyclerViewAdapter.setHasStableIds(true);
```
最后在adapter中重写了getItemId方法
```
@Override
    public long getItemId(int position) {
        return position;
    }
```

但是发现报Called attach on a child which is not detached错误

跟踪了下源码发现是由于LRecyclerViewAdapter有一个ArrowRefreshHeader所以导致itemid多了一位

因此在LRecyclerViewAdapter里的getItemId方法里的adjPosition是不是应该多减去一位？

**Comment by jdsjlzx** [comment]
1. 刷新参考：http://blog.csdn.net/jdsjlzx/article/details/52893469（再说Android RecyclerView局部刷新那个坑）

2.加载图片尽量使用Glide加载框架。

3. 关于position的问题，使用LRecyclerViewAdapter里面的getAdapterPosition(boolean isCallback, int position)方法，结合你的情况，mLRecyclerViewAdapter.getAdapterPosition(false, position);

/**
     *
     * @param isCallback whether position is from callback interface
     * @param position
     * @return
     */
    public int getAdapterPosition(boolean isCallback, int position) {
        if(isCallback) {
            int adjPosition = position - (getHeaderViewsCount() + 1);
            int adapterCount = mInnerAdapter.getItemCount();
            if (adjPosition < adapterCount) {
                return adjPosition;
            }
        }else {
            return  (position + getHeaderViewsCount()) + 1;
        }

        return -1;
    }


如有问题请再反馈！

**Comment by GavinAndre** [comment]
其实我主要是想反馈使用LRecyclerViewAdapter的情况下在DataAdapter中重写getItemId()方法后position多一位的问题
```
@Override
    public long getItemId(int position) {
        return position;
    }
```
这样重写后会报Called attach on a child which is not detached错误
需要将手动将position-1后才能正常执行
```
return position-1;
```
而使用LuRecyclerViewAdapter在DataAdapter中重写getItemId()方法后无需手动将position-1即可正常执行

我需要使用下拉刷新来刷新全部图片,并且还用到了分页,而为了防止图片重复下载浪费流量,我选择使用setTag的方式来将tag信息保存在viewholder里,而由于LRecyclerView的原因,所以需要将mDataAdapter和mLRecyclerViewAdapter都设置setHasStableIds为true,但是如果不重写getItemId()方法,会导致item错乱,因此必须要重写getItemId()方法返回position才能使setTag功能正常使用

**Comment by jdsjlzx** [comment]
LuRecyclerViewAdapter与LRecyclerViewAdapter区别就在于LRecyclerViewAdapter里面要考虑下拉刷新view所占的位置，如果你有自定义需要，就将position-1，另外你如果有addHeaderView，注意也要减去HeaderView的数量。

图片闪烁的问题，你可以参考下我给你的建议，我不设置下面的属性，也能解决问题。
mDataAdapter.setHasStableIds(true);
mLRecyclerViewAdapter.setHasStableIds(true);

**Comment by GavinAndre** [comment]
感谢你的建议和回复  我会学习一下你提供的刷新方式
对于使用tag的方式 虽说手动将position减去相应数量花不了什么时间 但是使用tag的方式应该也有不少人会用到 以防以后有别的人踩坑和考虑到框架的健壮性 建议在LRecyclerViewAdapter的getItemId()方法里加一个判断
```
@Override
    public long getItemId(int position) {
        if (mInnerAdapter != null && position >= getHeaderViewsCount()) {
            int adjPosition = position - getHeaderViewsCount();
            //判断是否mLRecyclerViewAdapter.setHasStableIds(true);
            if (hasStableIds()) {
                adjPosition--;
            }
            int adapterCount = mInnerAdapter.getItemCount();
            if (adjPosition < adapterCount) {
                return mInnerAdapter.getItemId(adjPosition);
            }
        }
        return -1;
    }
```

还有个疑问,就是既然LRecyclerViewAdapter里用了观察者模式,如果自己addHeaderView了后,为什么还要手动在DataAdapter里减去HeaderView的数量? getItemId()方法里的adjPosition不是已经减去HeaderViewsCount了吗
```
int adjPosition = position - getHeaderViewsCount();
```

还是说通过addHeaderView添加的headview不是保存在mHeaderViews这个list里的?
```
private ArrayList<View> mHeaderViews = new ArrayList<>();
```

**Comment by jdsjlzx** [comment]
如果你需要LRecyclerViewAdapter的position，就要考虑HeaderViewsCount，如果你使用HeaderViewsCount，则不需要考虑HeaderViewsCount。
