### ISSUE TITLE
到底部 上来没有出现加载更多的视图

### ISSUE THREAD

**Issue by tortoies** [jdsjlzx/LRecyclerView#114]
这个是放在viewpager的fragment中使用的，上拉不会出现加载更多的视图
代码如下
adapter = new GoodCollectionAdapter(mContext,null);//自己的适配器
gridLayoutManager = new GridLayoutManager(mContext,2);//自己的布局管理器

 lrvGoodCollection.setLayoutManager(gridLayoutManager);//lrv设置布局管理器
 lRecyclerViewAdapter = new LRecyclerViewAdapter(adapter);//lrv的适配器
lRecyclerViewAdapter.setSpanSizeLookup(new LRecyclerViewAdapter.SpanSizeLookup() {
            @Override
            public int getSpanSize(GridLayoutManager gridLayoutManager, int position) {
                        if (position <= 3){
                            return gridLayoutManager.getSpanCount();
                        }else {
                            return 1;
                        }
            }
        });
lrvGoodCollection.setAdapter(lRecyclerViewAdapter);//设置适配器

还想请问一下，设置不能下拉刷新之后，是不是也阻止了上拉加载更多？今天就碰到了这样的问题。

**Comment by jdsjlzx** [comment]
加载更多的事件要写，你如果不写，底层是不会触发的，详见EndlessLinearLayoutActivity类。

**Comment by tortoies** [comment]
谢谢大神
