### ISSUE TITLE
FooterView必须要在setAdapter之后添加

### ISSUE THREAD

**Issue by hardlove** [jdsjlzx/LRecyclerView#115]
添加FooterView必须要在setAdapter之后，弄了我一下午。坑啊

**Comment by jdsjlzx** [comment]
Sorry，给你带来了不好的体验！经过排查，已经修复了此问题！感谢你的反馈！新版本中setAdapter前后添加footerview都是可以的！请继续关注！

**Comment by hardlove** [comment]
ok

**Comment by davidgerka** [comment]
very good

**Comment by boly12345** [comment]
LinearLayoutManager layoutManager = new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false);
这样设置屏幕的第一页是空白的，必须得向左滑动才能滑出来
