### ISSUE TITLE
分页加载的时候，为什么必须要上一页铺满整个屏幕才能出现加载动画加载下一页？这里可以优化一下吗?

### ISSUE THREAD

**Issue by luochune** [jdsjlzx/LRecyclerView#116]
现在的版本已经修复这个问题了吗?，谢谢指教

**Comment by jdsjlzx** [comment]
自动加载是判断列表滑动到底部才会触发，如果没有“铺满整个屏幕”，怎么会知道到底部了呢？比如现在就一条数据，代码怎么知道你想加载更多呢？如果你实在需要，你可以自己修改源码定制！
