### ISSUE TITLE
请问DividerDecoration这里我setHeight 10dp，选项卡并没有下移，而是直接被截掉了。是什么原因

### ISSUE THREAD

**Issue by HH-Ding** [jdsjlzx/LRecyclerView#118]
![qq 20170222172844](https://cloud.githubusercontent.com/assets/11987172/23205364/92e4ed26-f924-11e6-8ecb-44a5234b3157.jpg)

**Comment by jdsjlzx** [comment]
已经修复，请使用最新的DividerDecoration类。

<img width="271" alt="1111" src="https://cloud.githubusercontent.com/assets/1652076/23215067/06b9b9a8-f94c-11e6-94a1-2b415917f509.png">
