### ISSUE TITLE
希望作者删除.idea .iml 这种没用的文件

### ISSUE THREAD

**Issue by tianshaokai** [jdsjlzx/LRecyclerView#119]
我去年git pull 过一次，今天git pull 导致了好多冲突的文件

**Comment by tianshaokai** [comment]
demo 点击报错
![image](https://cloud.githubusercontent.com/assets/6706496/23300879/91a99f48-fac2-11e6-9efb-159373fd9e74.png)

**Comment by tianshaokai** [comment]
demo 里几乎点击 一个 就会报错

**Comment by jdsjlzx** [comment]
由于api在春节期间进行了优化，变化比较大，建议你重新拉取代码。参考最新的实现，感谢关注！

**Comment by tianshaokai** [comment]
我就是拉的最新代码，对了添加header能不能添加自己的 viewholder 呢，而不是简单的添加一个view

**Comment by jdsjlzx** [comment]
addHeaderView(View view)与用viewholder是类似的，底层已经帮你实现了。所以并非你所理解的那样简单的添加一个view。封装框架的目的就是为了使用方便！

**Comment by tianshaokai** [comment]
那我的viewholder 怎么添加啊

**Comment by jdsjlzx** [comment]
参考demo中的MulItemGridLayoutActivity、BilibiliActivity类的实现。

**Comment by jdsjlzx** [comment]
如果没有问题，我先关闭该issue，如有问题你可以重新提issue！
