### ISSUE TITLE
在上拉下拉时，滑动不够流畅

### ISSUE THREAD

**Issue by xu819241519** [jdsjlzx/LRecyclerView#12]
上拉下拉时，没有recyclerView的流畅，用力一拉，手指离开屏幕时滑动就停止，recyclerview则在手指离开屏幕的时候还能根据惯性滑动一些距离。

**Comment by jdsjlzx** [comment]
你好，添加新功能导致了冲突，正在解决

**Comment by jdsjlzx** [comment]
已经解决了，请再试试吧
