### ISSUE TITLE
自定义下拉刷新无效

### ISSUE THREAD

**Issue by ezhuwx** [jdsjlzx/LRecyclerView#123]
LRecycleView 的setRefreshHeader(...)方法为private
LRecycleViewAdapter的setRefreshHeader方法设置以后 自定义VIew仅创建并未在LRecycleView 中调用

**Comment by jdsjlzx** [comment]
sorry，失误了，应该调用LRecycleView 中的setRefreshHeader方法，我已经修正，请使用最新版本
