### ISSUE TITLE
多次调用forceToRefresh 或refresh,列表会往下移动，OnRefreshListener也被多次调用

### ISSUE THREAD

**Issue by levenkk** [jdsjlzx/LRecyclerView#125]
顶部的刷新提示会随着 refresh 或 forceToRefresh的连续调用不断往下移动，OnRefreshListener也被多次调用

**Comment by jdsjlzx** [comment]
亲，为什么要连续调用呢？这个是特殊需求还是为了测试功能？

**Comment by levenkk** [comment]
项目中列表顶部有个搜索框，用户点击搜索时我调用refresh 去刷新列表，加载过程中可能多次点击搜索。
CommonPullToRefresh（android-Ultra-Pull-To-Refresh）或者其他的刷新框架多次调用是不会多次触发刷新事件的

**Comment by levenkk** [comment]
很多地方都用到了这个列表，如果手动控制的话就得在每个界面增加标识去控制

**Comment by levenkk** [comment]
在像在forceToRefresh里面那样加上mRefreshing的判断可能比较好吧，好比如刷新的过程中，在界面上下拉刷新不会多次触发刷新事件

**Comment by jdsjlzx** [comment]
好的，我尽快解决你说的问题！

**Comment by jdsjlzx** [comment]
最新版本1.3.8，已经在refresh方法里面做了是否正在刷新的判断！

**Comment by levenkk** [comment]
太感谢了，很及时

**Comment by jdsjlzx** [comment]
问题解决了吗

**Comment by levenkk** [comment]
已经解决了，谢谢
