### ISSUE TITLE
LuRecyclerView加载BUG图片

### ISSUE THREAD

**Issue by 284853845** [jdsjlzx/LRecyclerView#128]
![Uploading Screenshot_2017-03-15-18-38-08.png…]()

**Comment by 284853845** [comment]
![screenshot_2017-03-15-18-38-08](https://cloud.githubusercontent.com/assets/21049714/23977422/12681fae-0a29-11e7-9134-ad3459876783.png)

**Comment by jdsjlzx** [comment]
//setLayoutManager放在setAdapter之前即可，如下所示：

GridLayoutManager manager = new GridLayoutManager(this, 2);
mRecyclerView.setLayoutManager(manager);

mLuRecyclerViewAdapter = new LuRecyclerViewAdapter(mDataAdapter);
 mRecyclerView.setAdapter(mLuRecyclerViewAdapter);
