### ISSUE TITLE
自定义下拉刷新View

### ISSUE THREAD

**Issue by BiuBong** [jdsjlzx/LRecyclerView#129]
private void setRefreshHeader(IRefreshHeader refreshHeader) {
    this.mRefreshHeader = refreshHeader;
}
私有方法，设置不了自定义的下拉view

**Comment by jdsjlzx** [comment]
此问题已经修复，相关issue：https://github.com/jdsjlzx/LRecyclerView/issues/123
具体使用请参考：
https://github.com/jdsjlzx/LRecyclerView#自定义下拉刷新view

如有问题请反馈！
