### ISSUE TITLE
ArrowRefreshHeader有内存泄露问题

### ISSUE THREAD

**Issue by xu819241519** [jdsjlzx/LRecyclerView#13]
![screenshot_20160815-110003](https://cloud.githubusercontent.com/assets/9333146/17654643/da7444b8-62d7-11e6-86c4-2de0a4157dc7.png)
用leak canary检测内存泄露问题，报告ArrowRefreshHeader内存泄露

**Comment by jdsjlzx** [comment]
已经解决。
