### ISSUE TITLE
我把LRecyclerView加入coordinateLayout结果只要我先下拉在上拉，refresh就消失不了

### ISSUE THREAD

**Issue by LouisShark** [jdsjlzx/LRecyclerView#134]
![image](https://cloud.githubusercontent.com/assets/18005609/24069698/e5d112b8-0be8-11e7-9943-66b7b0dcf1db.png)

**Comment by LouisShark** [comment]
@jdsjlzx

**Comment by jdsjlzx** [comment]
参见：CollapsingToolbarLayoutActivity类

**Comment by LouisShark** [comment]
@jdsjlzx 我是把LRecyclerView放进fragment 然后动态添加这个fragment到 主 fragment，就是出现 手指下拉在向上拉，只要有向上的动作马上 刷新消失不了了，请大神指教一下。。

**Comment by LouisShark** [comment]
@jdsjlzx 我是把LRecyclerView放进fragment 然后动态添加这个fragment到 主 fragment，就是出现 手指下拉在向上拉，只要有向上的动作马上 刷新消失不了了，请大神指教一下。。
