### ISSUE TITLE
下拉刷新和adapter 封装库冲突崩溃

### ISSUE THREAD

**Issue by Biswangluo** [jdsjlzx/LRecyclerView#136]
https://github.com/CymChad/BaseRecyclerViewAdapterHelper
![qq 20170321142256](https://cloud.githubusercontent.com/assets/2362450/24134874/ff9016b2-0e41-11e7-965b-f774d89fb484.png)

**Comment by jdsjlzx** [comment]
你好，由于BaseRecyclerViewAdapterHelper于LRecyclerView功能上有些重合，会出现冲突，尽量不要一起使用。如果你实在想使用BaseRecyclerViewAdapterHelper，那么你可以参考LRecyclerView的demo中base包下面封装的adapter，如果不满足，你可以根据BaseRecyclerViewAdapterHelper的功能封装自己的adapter。

最后问一下你想实现什么功能呢？

**Comment by Biswangluo** [comment]
@jdsjlzx 主要实现多布局，之前一直用你的下拉刷新，公司开新项目之前 首页特别复杂 一拖N布局，就用了那个adapter封装库，他那个实现多布局实在简洁 快速省代码，手写多布局实在累。

**Comment by jdsjlzx** [comment]
关于多布局的实现，LRecyclerView的demo中也有提供，可以参考！也可以做到简洁 快速省代码。
