### ISSUE TITLE
LuRecyclerView在使用GridItemDecoration分割线添加的时候，会报错，LuRecyclerView应该怎么样画上分割线呢？

### ISSUE THREAD

**Issue by 284853845** [jdsjlzx/LRecyclerView#138]
LuRecyclerView在使用GridItemDecoration分割线添加的时候，会报错，LuRecyclerView网格布局时应该怎么样画上分割线呢？

**Comment by jdsjlzx** [comment]
增加了LuGridItemDecoration类，你可以先下载到本地使用验证下，如有问题请及时反馈！

说明：LuRecyclerView配套的都是以Lu开头的类。
