### ISSUE TITLE
下拉刷新高度有问题！

### ISSUE THREAD

**Issue by qq294685358** [jdsjlzx/LRecyclerView#14]
情况是这样，我在设置好了下拉刷新后，先用力下拉，然后惯性滑到底部，再用力上拉回到顶部，反复几次通过惯性到顶部的  “正在刷新”这个header高度有问题
![image](https://cloud.githubusercontent.com/assets/15881412/17693559/1a34a41c-63d2-11e6-98ce-108b598be2b4.png)
如图，希望能尽快解决

**Comment by qq294685358** [comment]
正常的 “下拉刷新”header高度应该是 下拉刷新这个4个字和loading图案竖向居中的  经过我这么反复几次拉到底又拉回顶部之后，会有这么个情况

**Comment by jdsjlzx** [comment]
亲，你在demo上面试一下，看看能不能出现问题！从你截图来看，初步怀疑是你布局文件里面的配置影响的，如果demo中能够复现问题，请及时反馈！另外贴一下你的布局文件我看看吧！

**Comment by qq294685358** [comment]
![screenshot_20160817-115840](https://cloud.githubusercontent.com/assets/15881412/17724145/2b0ff084-6472-11e6-99b5-8cdcd127f922.png)
![image](https://cloud.githubusercontent.com/assets/15881412/17724154/34219bf0-6472-11e6-9ad7-a33250c11eef.png)
![image](https://cloud.githubusercontent.com/assets/15881412/17724164/4c30c5d6-6472-11e6-860a-cccc3c348caf.png)
public class HospitalAdapter extends RecyclerView.Adapter<HospitalAdapter.HospitalViewHolder> {
    private Context mContext;
    private List<HospitaldBean> hospitalBeanList = new ArrayList<>();

    public HospitalAdapter(Context context, List<HospitaldBean> list) {
        this.mContext = context;
        this.hospitalBeanList = list;
    }

    @Override
    public HospitalViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return new HospitalViewHolder(LayoutInflater.from(mContext).inflate(R.layout.respital_item, parent, false));
    }

    @Override
    public void onBindViewHolder(HospitalViewHolder holder, int position) {
        holder.tv_name.setText(hospitalBeanList.get(position).getName());
        holder.tv_desc.setText(hospitalBeanList.get(position).getDesc());
        holder.tv_distance.setText(hospitalBeanList.get(position).getDistance());
        Picasso.with(mContext).load(hospitalBeanList.get(position).getImageurl()).into(holder.img_hospital);
    }

    @Override
    public int getItemCount() {
        return hospitalBeanList.size();
    }

    public static class HospitalViewHolder extends RecyclerView.ViewHolder {
        private TextView tv_desc, tv_name, tv_distance;
        private ImageView img_hospital;

        public HospitalViewHolder(View itemView) {
            super(itemView);
            tv_desc = (TextView) itemView.findViewById(R.id.tv_desc);
            tv_name = (TextView) itemView.findViewById(R.id.tv_name);
            tv_distance = (TextView) itemView.findViewById(R.id.tv_distance);
            img_hospital = (ImageView) itemView.findViewById(R.id.img_hospital);
        }
    }


以上基本就是关键代码了，我布局里只用了你的组件，经过测试也会出现我前面说的问题，你可以试试，在下拉刷新的时候别写任何逻辑，让这个下拉刷新header一直存在那里，然后反复上下滑到底就会出现问题

**Comment by qq294685358** [comment]
你的DEMO因为在下拉刷新里写了逻辑会加载进新数据，所以我测试了也没用

**Comment by qq294685358** [comment]
还有一个，你的下拉刷新的阻尼感觉比其他的下拉刷新阻尼大，能设置的吗，感觉下拉的时候要稍微使点劲多拉点才会出发下拉刷新

**Comment by jdsjlzx** [comment]
你好，从代码来看看不出问题！下拉刷新里写了逻辑会加载进新数据，这个不是正常逻辑吗？

无论是下拉刷新还是强制刷新，刷新完成后调用下面代码：

mRecyclerView.refreshComplete();
mLRecyclerViewAdapter.notifyDataSetChanged();

**Comment by qq294685358** [comment]
我知道在下拉刷新里写加载数据是正常逻辑，但是我想的是万一网络非常非常慢，在获取数据的过程中，用户无聊上拉下拉的，会看到这个header的头部不对，所以希望你有空的时候能试试我上面的代码，测试下。另外，下拉阻尼我这样说你听得懂吗，能不能写个方法可以动态设置下.

**Comment by tianshaokai** [comment]
@qq294685358  什么效果才是下拉阻尼啊，我没有理解啊，没做过这样的效果，你的问题解决了吗？

**Comment by qq294685358** [comment]
@tianshaokai 你去看看Ultra-Pull-To-Refresh  ，里面有说阻尼效果

**Comment by Biswangluo** [comment]
我也发现了同样的问题，改下Demo 在加载非常缓慢的情况下，快速往上翻，在惯性滚到顶部情况下，就会缺失一块 来回滚几次，下拉刷新几乎都滚没了

**Comment by Biswangluo** [comment]
![0e7f3be441c0af195b4a798c95143490](https://cloud.githubusercontent.com/assets/2362450/18236289/2c026244-7357-11e6-8681-f19e1ddaaa06.jpg)
![57c533550a4dc9a47f7281c48eb6d142](https://cloud.githubusercontent.com/assets/2362450/18236291/2fed69a8-7357-11e6-9e63-c8c86181a52b.png)

**Comment by jdsjlzx** [comment]
能录个小视频我看看吗？我没有复现这个问题！

**Comment by Biswangluo** [comment]
好吧 兄弟 不过Github 不能上传视频 我放到了 百度云盘里面   
[ http://pan.baidu.com/s/1hsqI5c4](url)
