### ISSUE TITLE
下拉的样式 无法设置啊

### ISSUE THREAD

**Issue by wxy520ll** [jdsjlzx/LRecyclerView#140]
recyclerView.setRefreshProgressStyle(ProgressStyle.BallSpinFadeLoader); //设置下拉刷新Progress的样式   没得setRefreshProgressStyle   方法

**Comment by jdsjlzx** [comment]
详见demo中的使用方法：https://github.com/jdsjlzx/LRecyclerView/blob/master/app/src/main/java/com/lzx/demo/ui/EndlessLinearLayoutActivity.java

**Comment by jdsjlzx** [comment]
自定义下拉刷新参考下面方法：
`

    public void setRefreshHeader(IRefreshHeader refreshHeader) {
        if(isRegisterDataObserver){
            throw new RuntimeException("setRefreshHeader must been invoked before setting the adapter.");
        }
        this.mRefreshHeader = refreshHeader;
    }
`
注意：setRefreshHeader方法必须在setAdapter方法之前调用才能生效。

自定义下拉刷新样式：
`
mRecyclerView.setRefreshProgressStyle(ProgressStyle.LineSpinFadeLoader);
mRecyclerView.setArrowImageView(R.drawable.ic_pulltorefresh_arrow);
`
