### ISSUE TITLE
a

### ISSUE THREAD

**Issue by wxy520ll** [jdsjlzx/LRecyclerView#141]
没得这个api。 是不是没来得及更新啊

**Comment by wxy520ll** [comment]
mLRecyclerViewAdapter.setOnLoadMoreListener ；

**Comment by jdsjlzx** [comment]
详见readme说明：

mRecyclerView.setOnLoadMoreListener(new OnLoadMoreListener() {
            @Override
            public void onLoadMore() {
                
            }
        });

你也可以参考demo！

**Comment by jdsjlzx** [comment]
你参考最新的api！
