### ISSUE TITLE
Gradle引用报错，是不是版本太高

### ISSUE THREAD

**Issue by hujiacheng-china** [jdsjlzx/LRecyclerView#146]
C:\Users\xiaobing\Desktop\ToggleExpandLayout-master\demo\build\intermediates\res\merged\debug\values-v23\values-v23.xml
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(34) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.
Error:(34) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.
C:\Users\xiaobing\Desktop\ToggleExpandLayout-master\demo\build\intermediates\res\merged\debug\values-v24\values-v24.xml
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
该怎么解决呢。？

**Comment by jdsjlzx** [comment]
clean下试试，根据log提示，看不出是LRecyclerView的问题！注意网络一定得能够连上google啊！

**Comment by hujiacheng-china** [comment]
不是网络的问题，我下载了demo，引用library，也是一样的错误，但是我将项目app的build.gradle的compileSdkVersion 改为25后就可以了，应该是library引用了25sdk版本的某个主题或者样式吗？我新建的工程试的，现在公式项目版本没那么高，该怎么办呢..?

**Comment by jdsjlzx** [comment]
你好，这种情况，你可以把library下载，修改版本号！

**Comment by hujiacheng-china** [comment]
我试过改为sdk21，但是也有别的问题，我看github其他重写的RecyclerView，大部分都要求sdk23以上。。看来是没办法了，好像有些方法在低版本的还没出现，显示找不到方法

**Comment by hardlove** [comment]
遇到一样的问题， 经过多次折腾无果，最终将android studio升级到2.3解决。

**Comment by jdsjlzx** [comment]
尽量更新studio到最新版本！
