### ISSUE TITLE
6.0上， ConnectivityManager 导致内存泄漏

### ISSUE THREAD

**Issue by hardlove** [jdsjlzx/LRecyclerView#147]
In com.lzx.demo:1.0:1.
* com.lzx.demo.ui.EndlessLinearLayoutActivity has leaked:
* GC ROOT static android.net.ConnectivityManager.sInstance
* references android.net.ConnectivityManager.mContext
* leaks com.lzx.demo.ui.EndlessLinearLayoutActivity instance

* Retaining: 5.7 KB.
* Reference Key: 0133529e-d6d0-439d-8cde-f087960094a1
* Device: samsung samsung SM-N9200 nobleltezc
* Android Version: 6.0.1 API: 23 LeakCanary: 1.5 00f37f5
* Durations: watch=5005ms, gc=122ms, heap dump=1624ms, analysis=89985ms

* Details:
* Class android.net.ConnectivityManager
|   static EXTRA_EXTRA_INFO = java.lang.String@1875203808 (0x6fc556e0)
|   static CALLBACK_RESUMED = 524300
|   static TYPE_WIFI = 1
|   static EXTRA_IS_ACTIVE = java.lang.String@1875275288 (0x6fc66e18)
|   static TYPE_ETHERNET = 9
|   static TYPE_NONE = -1
|   static NETID_UNSET = 0
|   static ACTION_TETHER_STATE_CHANGED = java.lang.String@1875053952 (0x6fc30d80)
|   static EXTRA_REALTIME_NS = java.lang.String@1875486464 (0x6fc9a700)
|   static TYPE_MOBILE_IA = 14
|   static TYPE_MOBILE_CMMAIL = 21
|   static ACTION_CAPTIVE_PORTAL_TEST_COMPLETED = java.lang.String@1875053368 (0x6fc30b38)
|   static TYPE_MOBILE_SUPL = 3
|   static MAX_NETWORK_REQUEST_TIMEOUT_MS = 6000000
|   static TETHER_ERROR_ENABLE_NAT_ERROR = 8
|   static TAG = java.lang.String@1874581496 (0x6fbbd7f8)
|   static EXTRA_IS_CAPTIVE_PORTAL = java.lang.String@1875117872 (0x6fc40730)
|   static EXTRA_NETWORK_REQUEST = java.lang.String@1875054600 (0x6fc31008)
|   static EXTRA_NETWORK_TYPE = java.lang.String@1875321864 (0x6fc72408)
|   static TYPE_DUMMY = 8
|   static ACTION_BACKGROUND_DATA_SETTING_CHANGED = java.lang.String@1875053176 (0x6fc30a78)
|   static EXTRA_ACTIVE_TETHER = java.lang.String@1874963600 (0x6fc1ac90)
|   static TYPE_MOBILE_ENT2 = 29
|   static CALLBACK_RELEASED = 524296
|   static MAX_NETWORK_TYPE_EX = 29
|   static TETHER_ERROR_IFACE_CFG_ERROR = 10
|   static MAX_RADIO_TYPE = 17
|   static TETHER_ERROR_DISABLE_NAT_ERROR = 9
|   static

![Uploading image.png…]()
参考：http://www.jianshu.com/p/7d4b55f7ed9f

**Comment by jdsjlzx** [comment]
感谢你的反馈！com.lzx.demo是demo，应用到项目的时候注意优化！
