### ISSUE TITLE
哥你在EndlessGridLayoutActivity这个界面设置每一页展示10条数据没有用啊

### ISSUE THREAD

**Issue by JiaWeiWan** [jdsjlzx/LRecyclerView#158]
在EndlessLinearLayoutActivity这个界面设置每一页展示10条数据数据下拉展示更多是有用的，但是EndlessGridLayoutActivity这个界面设置的就没有作用啊

**Comment by jdsjlzx** [comment]
EndlessGridLayoutActivity 你是不是一页展示的数据没有满屏呢？

**Comment by JiaWeiWan** [comment]
首先感谢你的回复！然后我在描述一下我的问题，我直接运行的你的demo   看到 
    /**服务器端一共多少条数据*/
    private static final int TOTAL_COUNTER = 24;

    /**每一页展示多少条数据*/
    private static final int REQUEST_COUNT = 10;

是不是因为你使用的REQUEST_COUNT = 10 的原因我不知道，因为在gridlayout模式下一页可以显示15条多一半，但是你设置的是每一页展示10条，又因为总数据是24条数据是超过了一页的，因为它有24条，但是直接滑动到底部显示了   "已经全部为你呈现了"   没有    Thread.sleep(1000);   延迟1秒。 在这个EndlessGridLayoutActivity界面

**Comment by jdsjlzx** [comment]
默认是10，你可以再修改这个默认值的！
