### ISSUE TITLE
item添加background没有效果

### ISSUE THREAD

**Issue by wuconghui** [jdsjlzx/LRecyclerView#159]
大神我想问一下，我在adapter的item布局中添加background想实现点击item变暗的效果，但是没有反应

**Comment by jdsjlzx** [comment]
你是在demo中修改的还是自己的项目呢？

**Comment by wuconghui** [comment]
在项目中，不过我给item的根布局设置clickable或者在代码中设置setOnclick事件就可以了，如果不这样的话就不行了

**Comment by jdsjlzx** [comment]
一般来说item设置android:background属性后，就能看到点击效果，你可以再排查下你的布局或者代码！
