### ISSUE TITLE
StickyHeaderFragment这个类的header有问题！

### ISSUE THREAD

**Issue by yaoxin2017** [jdsjlzx/LRecyclerView#164]
从竖屏切换到横屏，header 的宽度没有变化，应该是和item一样填充屏幕宽度才对。

**Comment by yaoxin2017** [comment]
我试了一下该项目的demo，却没有问题，后来发现是因为我在activity的清单里 配置了 android:configChanges="keyboardHidden|screenSize|orientation"  这样不会重建导致宽度没有适应横屏后的宽度。虽说不是bug，但是应用范围缩小了。

**Comment by yaoxin2017** [comment]
还有就是 当使用StickyHeaderFragment时，添加 addHeaderView(),自己添加的headerView 会显示在header的下面，而一般正常的需求是 添加addHeaderView（），就应该显示在最上面才对。不得已弃用了。

**Comment by yaoxin2017** [comment]
最后说一下，判断是否有header时 最好能在自己的adapter里判断，而不是返回head的下标，看了项目源码是根据当前和上一个head的下标相比，不相等就说明有新的header需要显示。我个人在interface StickyHeaderAdapter里添加了boolean hasHeader(int position);在StickyHeaderDecoration里 的
private boolean hasHeader(int position) {
        if (position == 0) {
            return true;
        }
//        int previous = position - 1;
//        return mAdapter.getHeaderId(position) != mAdapter.getHeaderId(previous);
//      改为由自己的适配器决定是否需要head布局
        return mAdapter.hasHeader(position);
    }

但是还是有问题，不弄了 ，，，

**Comment by jdsjlzx** [comment]
StickyHeaderFragment仅作参考，如果使用不方便，请换其他的实现方式，谢谢！
