### ISSUE TITLE
自定义DataAdapter出错

### ISSUE THREAD

**Issue by KobeBryant824** [jdsjlzx/LRecyclerView#166]
我用到https://github.com/CymChad/BaseRecyclerViewAdapterHelper 的通用适配器(非要用的话)，出现如下错误：
```
    java.lang.ClassCastException: com.github.jdsjlzx.recyclerview.LRecyclerViewAdapter$ViewHolder cannot be cast to com.chad.library.adapter.base.BaseViewHolder
                                                                                  at com.chad.library.adapter.base.BaseQuickAdapter.onViewAttachedToWindow(BaseQuickAdapter.java:65)
```

**Comment by jdsjlzx** [comment]
BaseRecyclerViewAdapterHelper 与LRecyclerView不兼容，不要一起使用！如果你非要使用，可以借鉴BaseRecyclerViewAdapterHelper 的实现，移植到你自己的DataAdapter里面。可以参考demo中的MultipleItemAdapter类。BaseRecyclerViewAdapterHelper 里面的功能你完全可以移植到你自定义的adapter里面。

**Comment by KobeBryant824** [comment]
你们两个adapter差不多了，BaseRecyclerViewAdapterHelper 的item滑动动画很实用
