### ISSUE TITLE
复用Fragment的问题

### ISSUE THREAD

**Issue by HH-Ding** [jdsjlzx/LRecyclerView#167]
viewpager下复用fragment，fragment的数量是根据服务器返回的数据动态生成。出现一种情况，当一个fragment里没有数据，切换到原先有数据的fragment，发现它的数据也被清了，用ListBaseAdapter.clear();

**Comment by jdsjlzx** [comment]
这个是框架的问题吗？

**Comment by HH-Ding** [comment]
不，我已经找到问题了，谢谢
