### ISSUE TITLE
addHeaderView 后下拉刷新会卡顿

### ISSUE THREAD

**Issue by SaltedFish999** [jdsjlzx/LRecyclerView#169]
headerview 中包含一个 RecyclerView， 然后添加到 LRecyclerView 后下拉刷新是会有些许的卡顿。请问这个怎么解决呢 ？ @jdsjlzx

**Comment by DonnyHe** [comment]
遇到相同问题

**Comment by libin1993** [comment]
在lrecyclerview里加上android:descendantFocusability="blocksDescendants"试下

**Comment by jdsjlzx** [comment]
参考：https://github.com/jdsjlzx/LRecyclerView/issues/165
