### ISSUE TITLE
DataAdapter是用户自己真正的adapter，用户自己定义，我自己定义的为什么传进去出错

### ISSUE THREAD

**Issue by danniu1314** [jdsjlzx/LRecyclerView#17]
mLRecyclerViewAdapter = new LRecyclerViewAdapter(mContext, new RoadShowAdapter());
我自己的adapter是继承的BaseAdapter，这个不行吗？是必须继承new RoadShowAdapter（），这个加进去报错。

**Comment by jdsjlzx** [comment]
mLRecyclerViewAdapter = new LRecyclerViewAdapter(mContext, new RoadShowAdapter()); 这样写是没有错的，你具体看看什么错误，最好能提供log。如果是滑动删除相关的功能，你自己的adapter就不能随意写了，要继承SwipeMenuAdapter，具体请详见demo！

**Comment by danniu1314** [comment]
我的adapter里面继承的BaseAdapter,用 getView(int poaition, View convertView, ViewGroup viewGroup),你们是实现的RecyclerView.ViewHolder，是必须用这个方式来加载自己的adapter吗，没LOG，我 new LRecyclerViewAdapter(mContext, new RoadShowAdapter())后面括号就报错，应该是adapter类型有问题，不是说是自己的adapter莫，还要必须修改后才可以吗

**Comment by jdsjlzx** [comment]
你自己的adapter只要extends RecyclerView.Adapter就没有问题！如demo中的DataAdapter：

private class DataAdapter extends ListBaseAdapter<ItemModel> 

public class ListBaseAdapter<T extends Entity> extends RecyclerView.Adapter

**Comment by tianshaokai** [comment]
@danniu1314  报错怎么会没有log呢，要是华为手机需要设置一下，才能打印出来log

**Comment by jdsjlzx** [comment]
华为手机一般不打印log，需要你手动打开！

**Comment by suman8848** [comment]
setSwipeMenuCreator() on Fragement not working

**Comment by jdsjlzx** [comment]
@suman8848 具体是什么情况呢？

**Comment by jdsjlzx** [comment]
滑动删除功能暂时删除！
