### ISSUE TITLE
快速上下滑动时，总会停住，然后要手指多次拨动列表才会滑动

### ISSUE THREAD

**Issue by axkza** [jdsjlzx/LRecyclerView#19]
不知道是不是滑动时，焦点给item获取了？

**Comment by jdsjlzx** [comment]
正在优化中，如果你有好的建议可以提出来

**Comment by qq294685358** [comment]
我也感觉到了这个问题，如果直接用官方的recyclerView就没事 怎么滑都流畅

**Comment by jdsjlzx** [comment]
最新版本是1.0.8，修改了一些bug。大家如果对滑动卡的问题有什么好的解决办法，请提出来！

**Comment by jdsjlzx** [comment]
已经优化，请使用最新版本
