### ISSUE TITLE
现在解决了会多出底部空白区域了吗？如何去隐藏？

### ISSUE THREAD

**Issue by danniu1314** [jdsjlzx/LRecyclerView#190]
不满一屏或者设置不能刷新，底部始终有一块空白区域。这块怎么能去掉？

**Comment by danniu1314** [comment]
我看你说已经设置了隐藏了。但目前我这里依然还是无法隐藏，关联的最新的版本

**Comment by jdsjlzx** [comment]
我的QQ：573842281，你找我看看！

**Comment by jdsjlzx** [comment]
详见：https://github.com/jdsjlzx/LRecyclerView#去除底部的加载更多的view
