### ISSUE TITLE
第一次加载数据后，不满一屏，有下一页数据，但无法上拉怎么办

### ISSUE THREAD

**Issue by renygit** [jdsjlzx/LRecyclerView#191]
不满一屏，无法上拉时，同时有下一页数据，希望做个判断，最下方可见如果等于itemCout，如果有下一页数据，自动执行加载更多（因为不满一屏，无法上拉）。

**Comment by jdsjlzx** [comment]
可以考虑多加载几条数据！

**Comment by jdsjlzx** [comment]
暂时关闭该issue
