### ISSUE TITLE
请问滑动时如何获取第一个可见item的postion以及最后一个item的postion

### ISSUE THREAD

**Issue by SL-Y** [jdsjlzx/LRecyclerView#195]
请问滑动时如何获取第一个可见item的postion以及最后一个item的postion

**Comment by jdsjlzx** [comment]
参考：http://blog.csdn.net/salute_li/article/details/52118504

**Comment by SL-Y** [comment]
谢谢。开始我就搜到了这篇，只是我调用方式错了。嘿嘿
