### ISSUE TITLE
请问LR有定位item的方法吗

### ISSUE THREAD

**Issue by HH-Ding** [jdsjlzx/LRecyclerView#197]
需求上有这个要求，请问lrecylerview有这个方法吗

**Comment by jdsjlzx** [comment]
参考：http://www.liuling123.com/2017/02/recyclerview-to-position.html

**Comment by HH-Ding** [comment]
但有Header的情况下，这个就不怎么管用

**Comment by jdsjlzx** [comment]
Header也会占用一个position，注意+1或者-1
