### ISSUE TITLE
LRecyclerView addHeaderView 后更新headerView数据的问题

### ISSUE THREAD

**Issue by zhujun77** [jdsjlzx/LRecyclerView#198]
我目前有一个需求： 内容展示 + 评论列表 ，我使用LRecyclerView的下拉刷新功能，将评论列表当成条目，内容当成HeaderView， 我实现了此功能。
问题出现在 下拉刷新后，我的内容发生变化 ，需要更新内容，于是我remove掉已有的headerView，重新添加一次headerView, 结果新的内容没有展示出来。
定位问题发现是 headerView被复用了，导致没有使用我新加的headerView。

提出此场景给作者，希望能讨论下解决思路

**Comment by jdsjlzx** [comment]
你直接更新headerView的内容不行吗？不用remove再add。直接更新就好！

**Comment by zhujun77** [comment]
嗯，最后也是这样处理的。
