### ISSUE TITLE
如何使用自己想要的刷新效果，我要的是SwipeRefreshLayout的效果，毕竟整个项目的效果要一致不是

### ISSUE THREAD

**Issue by pjh520** [jdsjlzx/LRecyclerView#2]

**Comment by jdsjlzx** [comment]
如果你不想使用自带的下拉，可以禁止此功能，搭配SwipeRefreshLayout使用。https://github.com/jdsjlzx/SimpleRecyclerView 这个不知道是否你想要的！

**Comment by yayaxiong** [comment]
@jdsjlzx 因为需要使用侧滑这些功能，所以就继续使用LRecyclerView，为了统一下拉刷新，使用的android-Ultra-Pull-to-Refresh，禁止自带的刷新的话recyclerView.setPullRefreshEnabled(false);这样下拉都没有反应了，第三方刷新框架也不能使用，现在是 recyclerView.setRefreshing(false)，在实际中有一点点小问题，不知道有更好的方法没有

**Comment by BlackJia** [comment]
@jdsjlzx  首先很感谢您分享的LRecyclerView功能很强大，不太想引入其他的RecyclerView，但是也希望实现 SwipeRefreshLayout的刷新效果。SimpleRecyclerView 可是解决冲突，但是其他的哪些侧滑删除等强大的功能又要加入其他的东西，真心希望大神能够给个结局方案

**Comment by jdsjlzx** [comment]
请使用最新版本，参考demo中的SwipeRefreshLayoutActivity类。里面有详细举例！

**Comment by BlackJia** [comment]
非常感谢。
