### ISSUE TITLE
onBottom

### ISSUE THREAD

**Issue by tianshaokai** [jdsjlzx/LRecyclerView#20]
建议换个名字，希望作者采纳

**Comment by jdsjlzx** [comment]
你有好的建议吗？起初打算用loadMore这样的名字的，但是我一想列表滚动到底部的不仅仅是能做加载更多，还可能有别的操作。我想让用户自己决定这里做什么。你感觉呢？

**Comment by tianshaokai** [comment]
@jdsjlzx  https://github.com/chrisbanes/Android-PullToRefresh
 (onPullDownToRefresh, onPullUpToRefresh) 我感觉这个开源库 里两个方法名字就不错，不知道作者是否考虑过呢，我觉得这里就是上拉加载更多，可能会在 最底部显示一些提示，比如没有网络啊，加载失败，就像新浪微博那样的

**Comment by jdsjlzx** [comment]
不知道你有没有下载demo体验下，(onPullDownToRefresh, onPullUpToRefresh) 这两个方法我感觉不是很恰当，LRecyclerView滚动到底部自动加载，不需要你上拉加载，至于下拉刷新，参考的是google最新的swiperefreshlayout的刷新方法。我们尽量走老外的思维！

**Comment by jdsjlzx** [comment]
可以动态为FooterView赋予不同状态（加载中、加载失败、滑到最底等）。

**Comment by tianshaokai** [comment]
嗯嗯，看到了功能很强大，不过要是有这样的需求 列表即需要下拉刷新 上拉加载 还需要 侧滑删除功能，这库是否支持呢

**Comment by tianshaokai** [comment]
@jdsjlzx  可以用autoLoadMore  其实你说的那些状态都是附加功能，具体的功能就是上拉加载更多

**Comment by jdsjlzx** [comment]
你还没有理解我的意思！onBottom这个可以除了加载更多之外的功能，比如到底部了，隐藏或者显示某个view等其他需求，这些就不属于autoLoadMore 的范畴了。比如某个公交站站名，你起名为北京路站，他就是个站名，具体你下车去哪里你自己决定，假如这个公交站名为万达广场站，那就不一样了，至少在名字上你就知道这个站下车后可以购物看电影。onBottom就是滑动到底部了，至于在onBottom方法里你是要加载更多还是隐藏或者显示某个view等其他逻辑，用户自己控制。

**Comment by tianshaokai** [comment]
@jdsjlzx 明白了 谢谢作者的耐心讲解

**Comment by tianshaokai** [comment]
EndlessLinearLayoutActivity 你的这个列表的 adapter 写的好复杂啊 ，我现在有个需求就是加一个下拉刷新上拉加载功能

**Comment by jdsjlzx** [comment]
EndlessLinearLayoutActivity只是个demo，其中的adapter你可以自己实现，demo中的adapter仅供演示！

**Comment by tianshaokai** [comment]
哦哦，com.github.jdsjlzx.recyclerview.LRecyclerView 作者能不能把这库分离一个简单的view呢，比如就有上拉加载和下拉刷新，和添加header 和 footer，我们公司现在限制方法个数不需要的不能加，下载了作者的源码发现，有好多侧滑的用不上，但必须都加进去

**Comment by tianshaokai** [comment]
@jdsjlzx LRecyclerViewAdapter 这adapter 太复杂了，虽然是demo 演示，其实也有参考的作用，发现这个adapter，充当了所有列表的adaper，让我们这些刚学recyclerview 的朋友来说，读起来有点吃力

**Comment by jdsjlzx** [comment]
EndlessLinearLayoutActivity 里面就满足你的需求，侧滑删除不是必须添加的，需求了添加，都是可以控制的。LRecyclerViewAdapter是基类里面的adapter，你至管用而不必关心他的实现。你只用维护好你自己的DataAdapter就行了，请你仔细再阅读下readme，还有demo。

填充数据

mDataAdapter = new DataAdapter(this);
mDataAdapter.setData(dataList);

mLRecyclerViewAdapter = new LRecyclerViewAdapter(this, mDataAdapter);
mRecyclerView.setAdapter(mLRecyclerViewAdapter);

注意：
DataAdapter是用户自己真正的adapter，用户自己定义；
LRecyclerViewAdapter提供了一些实用的功能，使用者不用关心它的实现，只需构造的时候把自己的mDataAdapter以参数形式传进去即可。

**Comment by tianshaokai** [comment]
@jdsjlzx  明白作者你的意思，只是我们公司不让随便加第三方库，都是把一些开源库的源码加到我们程序里，虽然说不用关系底层的具体实现，我看到有好多自己用不到的，就想删除了

**Comment by jdsjlzx** [comment]
你可以把libray导入你的工程，把不需要的类删除掉就可以了！

**Comment by tianshaokai** [comment]
@jdsjlzx  谢谢作者了

**Comment by tianshaokai** [comment]
@jdsjlzx  作者问你个问题啊，我去掉了滑动的相关代码，发现不能上拉加载了
