### ISSUE TITLE
你的适配器太定制了，不敢使用

### ISSUE THREAD

**Issue by github999999** [jdsjlzx/LRecyclerView#200]

**Comment by jdsjlzx** [comment]
mLRecyclerViewAdapter = new LRecyclerViewAdapter(mDataAdapter);
mRecyclerView.setAdapter(mLRecyclerViewAdapter);

LRecyclerViewAdapter是外面包裹的一层，mDataAdapter是你要自己实现的adapter，demo中提供的封装是我项目中实践总结，仅供参考。请注意区分，这个不做强制你使用，可以自定义！
