### ISSUE TITLE
当数据不满一屏的问题

### ISSUE THREAD

**Issue by chaopengTan** [jdsjlzx/LRecyclerView#202]
如果在第一次获取数据并设置的时候直接添加尾部布局，那么如果数据不满一屏，则尾部布局会显示在最下方，如果不添加尾部布局，那么如果数据已经一屏了我们却无法上拉加载更多。

 因为在加载数据完成之后无法预知数据是否足够能够填充满一屏

**Comment by jdsjlzx** [comment]
如题所示，你不知道加载的数据能否满屏，作为框架更不知道！在使用的过程中尽量避免此问题！毕竟你都在开发了，每页返回的数据应该是固定的吧，尽量让它填满屏幕。如果你硬要说接口中每页只返回了两三个不满一屏幕，那我也没有好办法了！

**Comment by chaopengTan** [comment]
已经找到处理方法，谢谢
