### ISSUE TITLE
老哥，强制刷新

### ISSUE THREAD

**Issue by snailManyw** [jdsjlzx/LRecyclerView#204]
当滑倒第一页末，偶尔出现一段空白item,上拉加载后到第二页的第一个或者第二个位置时，点击强制刷新，列表没有返回到顶部。。该怎么解决呀。。

**Comment by snailManyw** [comment]
与demo中MulItemGridLayoutActivity,点击强制刷新后没有回到顶部。

**Comment by jdsjlzx** [comment]
贴你的代码看看

**Comment by snailManyw** [comment]
mRecyclerView.setOnRefreshListener(new OnRefreshListener() {
            @Override
            public void onRefresh() {
                isRefresh = true;
                page = 1;
                recharge(shopNoTwo,startTime,endTime,page,flag);
            }
        });
        mRecyclerView.setOnLoadMoreListener(new OnLoadMoreListener() {
            @Override
            public void onLoadMore() {
                recharge(shopNoTwo,startTime,endTime,page,flag);
            }
        });
    mRecyclerView.refresh();

void recharge(String shopNoTwo, String startTime, String endTime, int page, final String falg) {
		     @Override
                    public void onResponse(RechargeModel response, int id) {
                        if(isRefresh){
                            mDataAdapter.clear();
                            isRefresh = false;
                        }
                        if(response.getCode()==0){
                            List<RechargeModel.DataBean> data = response.getData();
                            addItems(data);
                            mRecyclerView.refreshComplete(10);
                        }else {
                            mRecyclerView.setNoMore(true);
                        }
                    }
}
void addItems(List<RechargeModel.DataBean> list) {
        mDataAdapter.addAll(list);
        page++;
    }
当第二页第一个item滑出可见区域，再强制刷新就回到顶部了。
