### ISSUE TITLE
隐藏footer,设置View.GONE还是占用空间

### ISSUE THREAD

**Issue by liu4113231988** [jdsjlzx/LRecyclerView#205]
通过LRecyclerViewAdapter的getfooterview获取到footview之后，然后设置隐藏，确实是不显示了，单式还占用空间，有遇到的没？怎么解决？

**Comment by jdsjlzx** [comment]
什么场景需要你隐藏footer?

**Comment by june5753** [comment]
使用场景：当一页的数据 没有填充满一个界面时，最下面会有一个footer 在占用空间。
mLRecyclerViewAdapter.getFooterView().setVisibility(View.GONE); 如果加上这行，也会出现占用空间情况
如果换成这个：mLRecyclerViewAdapter.removeFooterView(); 不会占用空间，但是 上拉加载更多功能却禁用了。

**Comment by jdsjlzx** [comment]
mRecyclerView.refreshComplete(REQUEST_COUNT);

REQUEST_COUNT 为每次从接口取的数目，如果就一页，切总数小于REQUEST_COUNT，自动隐藏footer！
