### ISSUE TITLE
refreshComplete的参数是什么？有什么影响?

### ISSUE THREAD

**Issue by monkey008** [jdsjlzx/LRecyclerView#207]
README.md里说是每页加载数量
源码里 public void refreshComplete(int pageSize)  看变量名是页数
README.md里的mRecyclerView.refreshComplete();这个无参的方法已经没有了
如果每次都调用refreshComplete(0)会有什么影响吗？

**Comment by liukai2530533** [comment]
刷新的data数量

**Comment by jdsjlzx** [comment]
refreshComplete(int pageSize)  pageSize 是一次请求的数量,根据这个数量进行分页!
