### ISSUE TITLE
使用Gradle方式引用  com.github.jdsjlzx:LRecyclerView:1.4.3，会有方法找不到

### ISSUE THREAD

**Issue by ieewbbwe** [jdsjlzx/LRecyclerView#211]
我是先从git上拉去的代码当成库引入到我的工程，之后我将这种方式改为了Gradle的依赖引入。
但是之前的代码里面，LRecycleView会有一些方法找不到：loadMoreComplete();refreshComplete();setFootViewHint()。怀疑是否是库上面的版本还未更新导致，请作者查看

**Comment by jdsjlzx** [comment]
api有变动,详细使用参考demo中的EndlessLinearLayoutActivity类!
