### ISSUE TITLE
第一条和最后一条分割线问题

### ISSUE THREAD

**Issue by cwjlxh** [jdsjlzx/LRecyclerView#215]
建议增加分割线的设置，可以设置是否显示第一条或者显示最后一条分割线

**Comment by jdsjlzx** [comment]
你可以在item布局中实现!不用太复杂的逻辑!

**Comment by cwjlxh** [comment]
这样不够灵活，还是建议加入显示分割线的设置操作，就是在builder里加个方法，然后在显示的分割线的地方处理一下就可以了
