### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wanyt** [jdsjlzx/LRecyclerView#22]
我认真研究了代码，我感觉LRecyclerView里面的代码有点混乱，而且ViewPager和Item的Swipe功能可以抽取出来，再自定义两个RecyclerView类。

**Comment by jdsjlzx** [comment]
感谢提出意见！后续会优化下代码的！至于ViewPager和Item的Swipe功能再抽出来两个RecyclerView类，估计不太现实，用户不一定喜欢这样。我有时也很无奈，此后尽量不再添加其他功能了！如果你有更好的建议或者方案，请告诉我！

**Comment by jdsjlzx** [comment]
swipe滑动功能放到本地实现，libray已经去掉！
