### ISSUE TITLE
setLayoutManager的问题

### ISSUE THREAD

**Issue by 1479HuangDa** [jdsjlzx/LRecyclerView#227]
当再次设置不同的LayoutManager时出现类型转换异常

**Comment by jdsjlzx** [comment]
参考demo：https://github.com/jdsjlzx/LRecyclerView/blob/master/app/src/main/java/com/lzx/demo/ui/ListDragMenuActivity.java
代码如下：
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == android.R.id.home) {
            finish();
        } else if (item.getItemId() == R.id.menu_grid) {
            mRecyclerView.setLayoutManager(new GridLayoutManager(this, 2));
            mRecyclerView.setAdapter(mLRecyclerViewAdapter);//必须重新setAdapter

        }else if (item.getItemId() == R.id.menu_linear) {
            mRecyclerView.setLayoutManager(new LinearLayoutManager(this));

        }
        return true;
    }
