### ISSUE TITLE
SectionLayoutActivity加入下拉刷新的功能后下拉界面与Section冲突

### ISSUE THREAD

**Issue by qiaokang** [jdsjlzx/LRecyclerView#23]
SectionLayoutActivity Demo中没有下拉刷新的功能，按照Demo中其他的例子加入下拉刷新的功能后，下拉界面会出现在第一个Section的下方。

**Comment by jdsjlzx** [comment]
SectionLayoutActivity分组列表一般不建议下拉刷新了！如有需要，请结合swiperefreshlayout实现！
