### ISSUE TITLE
利用LRecycleView，首次进去列表页面后会自动下拉刷新！

### ISSUE THREAD

**Issue by LiuJiaWen123** [jdsjlzx/LRecyclerView#235]
就是刚进来包含 LRecycleView 页面的时候，列表会自动出现下滑刷新的动画，这一点应该是不好的，请问怎么改善？！

**Comment by jdsjlzx** [comment]
mRecyclerView.refresh();  这句代码就是自动下拉刷新,你可以去掉!

**Comment by LiuJiaWen123** [comment]
但是把这句话去掉之后第一次进来页面的时候数据又显示不出来
![image](https://user-images.githubusercontent.com/22657273/30839302-a51e0d46-a2a3-11e7-9f14-d9680cb6be64.png)

**Comment by LiuJiaWen123** [comment]
你看看上文的代码，我把这两句都试了一遍；
但是查看你的源码之后我发现你的foreceTorefresh是refresh的扩展，所以只有当这两句中一句被执行之后，数据才能显示出来

**Comment by LiuJiaWen123** [comment]
问题解决了，谢了哈，我自己找到了
