### ISSUE TITLE
xml报错

### ISSUE THREAD

**Issue by cjcj125125** [jdsjlzx/LRecyclerView#247]
平时一直用着挺爽，最近一直xml报错，并且报错的也不具体，希望大佬看看，谢谢
![qq 20171030201838](https://user-images.githubusercontent.com/20206579/32170465-97e6bda4-bdaf-11e7-9557-086ef8ea857f.png)

**Comment by cjcj125125** [comment]
这里报错信息一直指向com.github.jdsjlzx.recyclerview.LRecyclerView的xml的10行，无奈了

**Comment by jdsjlzx** [comment]
跟其他三方库中有重名的类，请注意排查！
