### ISSUE TITLE
footview显示不全

### ISSUE THREAD

**Issue by tmxd09887** [jdsjlzx/LRecyclerView#248]
mRecyclerView.setFooterViewColor(R.color.black, R.color.black ,R.color.gray);
定义了以后，只有背景色生效，字体完全看不见，loading的图标也也看不到

但是在public void onLoadMore(){ 注释掉mRecyclerView.refreshComplete(40);
loading字体和图标就能看到了，但是也无法加载更多了。

这是什么原因？

谢谢

下面是部分代码

`
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        View rootView = inflater.inflate(R.layout.home_fragment, container, false);

        mRecyclerView = (LRecyclerView) rootView.findViewById(R.id.recycler_view);

        GridLayoutManager layoutManager = new GridLayoutManager(context,4);
        mRecyclerView.setLayoutManager(layoutManager);

        mDataAdapter = new homeAdapter(context);

        mLRecyclerViewAdapter = new LRecyclerViewAdapter(mDataAdapter);
        mRecyclerView.setAdapter(mLRecyclerViewAdapter);

        //设置底部加载颜色
        mRecyclerView.setFooterViewColor(R.color.black, R.color.black ,R.color.gray);

        //设置底部加载文字提示
        mRecyclerView.setFooterViewHint("Loading","已经全部为你呈现了","网络不给力啊，点击再试一次吧");

        mRecyclerView.setHasFixedSize(true);

        initListener();

        return rootView;
    }

    private void initListener() {

        mRecyclerView.setOnRefreshListener(new OnRefreshListener() {
            @Override
            public void onRefresh() {
                mCurrentCounter = 0;
                pageNum = 0;
                getP().loadData(1, "REFRESH_DATA", mTitle);
                mRecyclerView.refreshComplete(10);
            }
        });

        mRecyclerView.setOnLoadMoreListener(new OnLoadMoreListener() {
            @Override
            public void onLoadMore() {
                if (mCurrentCounter < TOTAL_COUNTER) {
                    pageNum += 1;
                    getP().loadData(pageNum,"MORE_DATA",mTitle);
                    mRecyclerView.refreshComplete(40);
                } else {
                    //the end
                    mRecyclerView.setNoMore(true);
                }
            }
        });

        mRecyclerView.refresh();`

**Comment by jdsjlzx** [comment]
请在demo中复现下，谢谢！

**Comment by tmxd09887** [comment]
抱歉，时间久了，代码没留下来。谢谢。
