### ISSUE TITLE
setNoMore(true) 底部没有显示

### ISSUE THREAD

**Issue by liihuu** [jdsjlzx/LRecyclerView#250]
为啥调用了setNoMore(true) 底部没有显示文字？我没有修改默认文字

**Comment by qhzzl** [comment]
setNoMore(true);之后底部脚布局就隐藏了

**Comment by jdsjlzx** [comment]
`
mRecyclerView.setOnLoadMoreListener(new OnLoadMoreListener() {
            @Override
            public void onLoadMore() {
                if (mCurrentCounter < TOTAL_COUNTER) {
                    // loading more
                    requestData();
                } else {
                    //the end
                    mRecyclerView.setNoMore(true);
                }
            }
        });
`

setNoMore(true);意思是加载数据完了！


`
/**
     * 设置是否已加载全部
     * @param noMore
     */
    public void setNoMore(boolean noMore){
        mLoadingData = false;
        isNoMore = noMore;
        if(isNoMore) {
            mLoadMoreFooter.onNoMore();
        } else {
            mLoadMoreFooter.onComplete();
        }
    }
`

demo中有详细的例子！
