### ISSUE TITLE
在Adapter中使用RecyclerView，下拉刷新不流畅，禁止RecyclerView竖直滑动也不行

### ISSUE THREAD

**Issue by NICOLITE** [jdsjlzx/LRecyclerView#251]
在Adapter中使用RecyclerView，下拉刷新不流畅，禁止RecyclerView竖直滑动也不行

**Comment by jdsjlzx** [comment]
尽量不这样嵌套，容易导致滑动冲突，暂时没有好的解决办法。如果需要可以嵌套listview！
