### ISSUE TITLE
lrecyclerview瞬间回到顶部

### ISSUE THREAD

**Issue by wuconghui** [jdsjlzx/LRecyclerView#256]
作者您好，我项目中有一个回到顶部功能我通过recyclerView.smoothScrollToPosition(0);实现回滚到顶部
 通过recyclerView.setLScrollListener的
 @Override
            public void onScrolled(int distanceX, int distanceY) {
                if (distanceY > 1000) {
                    floatButton.setVisibility(View.VISIBLE);
                } else {
                    floatButton.setVisibility(View.GONE);
                }
            }
可以控制floatButton的显示和隐藏，但是如果数据较多的话，回滚时间就会很长，
我如果使用 // manager.scrollToPositionWithOffset(0, 0);能瞬间回到顶部，但是按钮floatButton无法正确控制显示和隐藏，应为distanceY值没有随着列表回到顶部而变为0，请问您有什么好的解决方法吗

**Comment by jdsjlzx** [comment]
参考：https://github.com/jdsjlzx/Community

**Comment by Gui-Ji** [comment]
请问该功能如何解决的
