### ISSUE TITLE
SrcollView + LRecycleView 嵌套  

### ISSUE THREAD

**Issue by 932236581** [jdsjlzx/LRecyclerView#266]
SrcollView + LRecycleView 滑动冲突解决了 但是  下拉刷新 没出来 不知道怎么回事 因为 需求上是要在列表里面刷新 目测 不知道怎么调整

**Comment by jdsjlzx** [comment]
你好，描述再清楚点！

不知道你是否想做这个效果呢？
![image](https://user-images.githubusercontent.com/1652076/35342607-73db9c5c-0163-11e8-834a-cc1a23c81093.png)

**Comment by 932236581** [comment]
![image](https://user-images.githubusercontent.com/19973630/35365252-79895d9c-01ae-11e8-837b-097d175c29ff.png)
具体是这样  我嵌套ScrollView 下拉刷新 就卡卡的
