### ISSUE TITLE
怎么获取滚动状态

### ISSUE THREAD

**Issue by idealcn** [jdsjlzx/LRecyclerView#27]
LRecyclerView.setLScrollListener(LScrollListener listener);
接口方法里无法获取页面滚动的状态。
×××××××××
我需要做的是，当页面不滚动时才去加载数据。我需要知道页面的滚动状态。
或者你有别的好的想法也可以。谢谢！！！

**Comment by jdsjlzx** [comment]
具体要实现什么功能呢？

**Comment by jyh149129** [comment]
我也需要这个，比如有大量网络图片的列表页，滚动状态时就暂停图片加载，列表滚动停止才开始加载

**Comment by jdsjlzx** [comment]
void onScrollStateChanged(int state);   增加这样一个接口满足你们的需求吗？

**Comment by jdsjlzx** [comment]
已经增加响应接口！
