### ISSUE TITLE
当LRecyclerView遇上 CoordinatorLayout 和 AppBarLayout之后

### ISSUE THREAD

**Issue by scxingm** [jdsjlzx/LRecyclerView#275]
上拉加载更多，加载事件会被延迟触发！！！
<CoordinatorLayout>
    <AppBarLayout>
        <Toolbar />
    </AppBarLayout>
    <DrawerLayout>
        <LRecyclerView>
        </LRecyclerView>
    </DrawerLayout>
</CoordinatorLayout>

**Comment by scxingm** [comment]
<pre>
<CoordinatorLayout>
    <AppBarLayout>
        <Toolbar />
    </AppBarLayout>
    <DrawerLayout>
        <LRecyclerView>
        </LRecyclerView>
    </DrawerLayout>
</CoordinatorLayout>
</pre>

**Comment by scxingm** [comment]
<code>
<CoordinatorLayout>
    <AppBarLayout>
        <Toolbar />
    </AppBarLayout>
    <DrawerLayout>
        <LRecyclerView>
        </LRecyclerView>
    </DrawerLayout>
</CoordinatorLayout>
</code>

**Comment by scxingm** [comment]
< CoordinatorLayout>
    < AppBarLayout>
        < Toolbar />
    < /AppBarLayout>
    < DrawerLayout>
        < LRecyclerView>
        < /LRecyclerView>
    < /DrawerLayout>
< /CoordinatorLayout>

**Comment by jdsjlzx** [comment]
此问题已经解决，请使用最新版本。
compile 'com.github.jdsjlzx:LRecyclerView:1.5.0'
