### ISSUE TITLE
下拉加载完成有bug

### ISSUE THREAD

**Issue by yitongUp** [jdsjlzx/LRecyclerView#277]
我使用的是1.5.1,。
目前，每次下拉加载完成都要调用refreshComplete方法才能使得header消失。
但问题的关键是为什么我每次都要设置要显示的item数？
如果接口返回了空数据，我就不做数据刷新，但是要我设置item数为0么？
Ps:不知道为啥qq不能搜索群了。好像是开会的原因？

**Comment by yitongUp** [comment]
比如我在网络请求。如果正常返回，我设置的pageSize是data的全部。那如果有异常，我该怎么办。。。head消失不了了。。。

**Comment by jdsjlzx** [comment]
显示的item数是为了控制该不该显示底部的加载状态view，由于我不知道你一次加载的数据是否能够铺满一屏幕，所以就让你传个固定pageNumber！

**Comment by jdsjlzx** [comment]
QQ群可以搜的，另外尽量尝试新版本吧！
