### ISSUE TITLE
如果数据分页容量不满一屏 无法上拉刷新

### ISSUE THREAD

**Issue by monkey008** [jdsjlzx/LRecyclerView#281]
后台每一页只给了5条数据 不足一屏 无法上拉刷新 最后和后台协商换成每页10条数据了
如果遇到不讲理的后台岂不是要抓瞎了？？？

**Comment by jdsjlzx** [comment]
我的初衷是如果不满一屏幕，可以下拉刷新。可还是很多人有需求想上拉刷新，后面我加上这个功能！
