### ISSUE TITLE
请问你的这个swip部分和https://github.com/yanzhenjie/SwipeRecyclerView/有什么区别

### ISSUE THREAD

**Issue by nimengbo** [jdsjlzx/LRecyclerView#29]
请问你的这个swip部分和https://github.com/yanzhenjie/SwipeRecyclerView/   有什么区别

**Comment by markzhai** [comment]
https://github.com/TUBB/SwipeMenu/
还有这个

**Comment by jdsjlzx** [comment]
统一回答，功能都是类似的，区别不大！请大家根据需要选择使用！LRecyclerView的swipe部分借鉴了SwipeRecyclerView，严振杰 （作者）本人是知晓此事的！
