### ISSUE TITLE
希望能支持EmptyView

### ISSUE THREAD

**Issue by daiwj** [jdsjlzx/LRecyclerView#30]
希望能支持EmptyView，在没有数据的情况也能支持下拉刷新。

**Comment by jdsjlzx** [comment]
可以为EmptyView添加点击事件，请求数据！参考：https://github.com/stay4it/Community

**Comment by daiwj** [comment]
我从你的demo apk 上没有发现这个效果。

需求是下拉操作无论当前有无数据都可以下拉，同时，没有数据时显示一个EmptyView提示用户重新下拉加载，希望可以添加这样的功能。

**Comment by jdsjlzx** [comment]
没有数据时显示一个EmptyView，此时的RecyclerView是隐藏的。无论是淘宝还是其他app，都是类似的处理。没有网络或者加载出错，点击中间的view可以重新加载！参考：https://github.com/stay4it/Community 这个效果的实现！

至于你的需求：无论当前有无数据都可以下拉 是产品要求还是自己测试呢？  你可以参考一下主流app的实现。

**Comment by daiwj** [comment]
这个需求是产品提的，没办法...
单纯的使用ListView/RecyclerView是实现不了这个效果。我目前的做法是 自己实现了一个下拉刷新，不过是在外层包裹的一层。QQ消息列表界面是可以做到的，不知道是不是 在没有数据的时候放了一个HeaderView或者FooterView。

**Comment by Tiannuo** [comment]
只需要在获取数据list的size==0的时候让 Recyclerview.setVisibility(View.VISIBLE);就可以
