### ISSUE TITLE
现在怎么无法从仓库下载了

### ISSUE THREAD

**Issue by zouchuqu** [jdsjlzx/LRecyclerView#308]
报错提示:Failed to resolve: com.github.jdsjlzx:LRecyclerView:1.5.0

    repositories {
        maven { url "https://jitpack.io"}
    }
 implementation 'com.github.jdsjlzx:LRecyclerView:1.5.0'

试了很多次都不能下载，试了其他的资源是可以的，不知道是哪里的原因

**Comment by jdsjlzx** [comment]
注意翻墙！只要网好就能下载！

**Comment by zouchuqu** [comment]
已经翻墙了，我用Google 可以搜索信息，也就是我可以访问外网，但是不能下载 LRecyclerView，Android studio 试了很多次了，有没有jar包的链接？ 去年的时候好像都是可以下载的。
