### ISSUE TITLE
 Called attach on a child which is not detached: ViewHolder

### ISSUE THREAD

**Issue by yanyonghua** [jdsjlzx/LRecyclerView#313]
LRecyclerView作者：
你好，
在这个recyclerview跳转到另一个界面取值回到当前页面后，出现这个问题，不管我用position+1还是position-1，还是出现崩溃的情况。

**Comment by jdsjlzx** [comment]
你好，不好意思给你造成了不好的体验。

demo中的ListDragMenuActivity这个类你参考下，关于position的使用参考：

@Override
        public void onSwiped(RecyclerView.ViewHolder viewHolder, int direction) {
            int position = mLRecyclerViewAdapter.getAdapterPosition(true,viewHolder.getAdapterPosition());
            TLog.error("onSwiped position " + position);
            mDataAdapter.getDataList().remove(position);
            mDataAdapter.notifyItemRemoved(position);
        }

由于header和footer都会占用item，计算postion的时候要考虑这个。详情参考ListDragMenuActivity类的使用，如果还有问题，请贴下log。

**Comment by yanyonghua** [comment]
非常感谢你及时的回答，原来是直接把ViewHolder传出来了。我是直接把position 。我没有看过demo。是我们公司之前同事用到这个库。非常棒。

**Comment by jdsjlzx** [comment]
感觉支持，有好的建议可以反馈，共同进步！
