### ISSUE TITLE
LRecyclerView与LRecyclerView有什么区别

### ISSUE THREAD

**Issue by xadlovezy** [jdsjlzx/LRecyclerView#326]
LRecyclerView与LRecyclerView有什么区别大神？

**Comment by jdsjlzx** [comment]
不要SwipeRefreshLayout与LRecyclerView一起使用，会有冲突，为了更好的满足广大用户，新增了LuRecyclerView类，可以与SwipeRefreshLayout搭配使用，详细请参考SwipeRefreshLayoutActivity类的实现。
