### ISSUE TITLE
api设计的一些建议

### ISSUE THREAD

**Issue by chenzhenboy** [jdsjlzx/LRecyclerView#34]
先要感谢作者的开源项目,已经在项目中用到了,嘿嘿
1,接口尽量小一点,比如LScrollListener建议拆分成几个小接口,或者使用抽象
2,增加一些自定义属性,比如刷新的样式,这些可以xml中指定
3,new LRecyclerViewAdapter(mAdapter), RecyclerViewStateUtils.setFooterViewState这类的操作可以抽取为LRecycleView的api,使用工具类会增加使用成本
4,AVLoadingIndicatorView的颜色好像没有提供api或者属性,外部不知道怎么去改颜色
不知道提的对不对,只是个人的看法.

**Comment by jdsjlzx** [comment]
感谢支持！如有好的想法，可以把源码fork了，按照你的想法修改一下，如果没有问题，我可以合并到主线中！好的框架离不开大家的支持和维护！

**Comment by jdsjlzx** [comment]
部分采纳了你的建议！
