### ISSUE TITLE
设置了emptyView导致数据没有办法显示

### ISSUE THREAD

**Issue by qiu1992** [jdsjlzx/LRecyclerView#37]
有这么一个需求，刚刚进入界面的时候，显示emptyview，与此同时请求网络数据，网络数据请求回来之后，emptyview隐藏，同时显示列表视图。现在是，只要emptyview出现了，列表视图就没有办法显示。翻了下源码，LRecyclerView这个类，DataObserver里面的onChanged只有在setAdapter的时候才会调用。目前自用的版本，新增了一个public方法，把DataObserver的成员变量暴露出去，然后有需要再调用。
eg.
public void onDataChange ()
{
      mDataObserver.onChanged();
}

**Comment by jdsjlzx** [comment]
你可以为empty view提供点击事件，重新获取数据。列表有数据后，mLRecyclerViewAdapter.notifyDataSetChanged();即可！
