### ISSUE TITLE
footView有一个显示方面的小问题

### ISSUE THREAD

**Issue by qiu1992** [jdsjlzx/LRecyclerView#38]
只要调用了RecyclerViewStateUtils里面的方法setFooterViewState，就会把footView的状态改成显示。这样会导致一个问题，比如强制下拉刷新（把数据清除，然后notifyxxxxx），这个时候，界面就会看到上次设置的footerview的内容，因为状态已经设置为visiable。也就是说，如果有请求数据，那么先会闪现footerview的内容，然后再显示列表视图，这样用户体验不好。目前自用版本做法还是暴露一个方法，可以从外部设置footerview的显示状态，但感觉不是十分优雅。。。

**Comment by jdsjlzx** [comment]
现在有没有更好的实现方式呢？能否更详细的说明下你所说的问题呢

**Comment by jdsjlzx** [comment]
最新的版本已经对此问题进行了优化！
