### ISSUE TITLE
坑逼

### ISSUE THREAD

**Issue by HOHDH** [jdsjlzx/LRecyclerView#39]
怎么搞的，非要应用24以上的v4包，你行不行啊

**Comment by jdsjlzx** [comment]
你好，你可以 LRecyclerview_library/build.gradle配置文件！library里面配置都是最新版本！

**Comment by jdsjlzx** [comment]
只要网络可以，都是可以在线下载依赖包的！如果实在不行，就把代码下载下来，你本地修改下版本！
