### ISSUE TITLE
关于color的问题

### ISSUE THREAD

**Issue by EthanCo** [jdsjlzx/LRecyclerView#41]
这几个命名在Android使用比较普遍
colorPrimary
colorPrimaryDark
colorAccent  

由于我项目中的style、color文件是放在单独的module中的，引入LRecyclerView后，导致会先加载LRecyclerView的color。  

希望在LRecyclerView中，将这几个命名改为其他的

**Comment by jdsjlzx** [comment]
colorPrimary
colorPrimaryDark
colorAccent

是Android自带的，改不了名字。你本地项目可以定义覆盖了就可以了。

**Comment by jdsjlzx** [comment]
如果实在不行，你把libray下载到本地，自己修改了libray代码引用就行！

**Comment by EthanCo** [comment]
恩，行
