### ISSUE TITLE
Entity的作用是什么

### ISSUE THREAD

**Issue by EthanCo** [jdsjlzx/LRecyclerView#43]
```
public abstract class Entity implements Serializable{
    public int id;
    public int type; // content type
}
```

这个类中 id 和 type 的作用是什么 ?  我查看引用到的地方，都不是和LRecyclerView实现所必须的，那么为什么还需要这两个属性呢 ? 

还有，这个Entity类能改为接口形式么 ?  有时候对象是继承自其它类的，不方便再继承Entity

**Comment by jdsjlzx** [comment]
Entity属于demo工程的实体类，不属于LRecyclerView 框架中的类。demo是为了演示，请注意区分！demo中任何类仅供参考！

**Comment by EthanCo** [comment]
Σ( ° △ °|||)︴
