### ISSUE TITLE
分割线问题

### ISSUE THREAD

**Issue by mytaihong** [jdsjlzx/LRecyclerView#44]
当添加分割线时    下拉刷新的View下也有一条个分割线显示， 应该没有

**Comment by jdsjlzx** [comment]
你好，这个问题我会看看的！你暂时可以在item的底部添加一个1px的view（横线）来替代分割线。

**Comment by mytaihong** [comment]
谢谢你的回复  还有救是上拉显示状态的view也出现多余的分隔线  显示不美观   怎么解决呢？？

**Comment by jdsjlzx** [comment]
解决方案同上！

**Comment by love-311** [comment]
好吧，谢谢你的回复，我暂时也是这么处理的，谢谢大神的好框架，非常好用。

**Comment by love-311** [comment]
刚发现其实只需要在DividerItemDecoration画线的时候少画一条就可以了。。

**Comment by jdsjlzx** [comment]
你可以贴一下你的代码，给大家分享下！
