### ISSUE TITLE
希望支持RecyclerView局部刷新

### ISSUE THREAD

**Issue by YLBFDEV** [jdsjlzx/LRecyclerView#45]
实现方式如下

![API说明](http://f.wetest.qq.com/gqop/10000/20000/LabImage_72d4b9657651b900a556308f9f0ef9a7.png)

![API方法](http://f.wetest.qq.com/gqop/10000/20000/LabImage_2973db019c5f03e391dad511d889930a.png)

[参考文章链接](http://wetest.qq.com/lab/view/176.html)

[参考文章链接](http://stackoverflow.com/questions/33176336/need-an-example-about-recyclerview-adapter-notifyitemchangedint-position-objec)

**Comment by jdsjlzx** [comment]
已经修改验证并提交，请你验证下，如果没有问题，请回复下，我将尽快发布新版本！
