### ISSUE TITLE
侧滑删除

### ISSUE THREAD

**Issue by zktzktzkt** [jdsjlzx/LRecyclerView#49]
侧滑删除有个很大的问题，删第一条还正确，当删第二条的时候就会自动删除第三条，第二条并没删，再删第二条的时候又接着删第三条。。。看到请麻烦速度回复解决一下。。鄙人太菜没弄出来。。因为项目用的就是你的这个侧滑删除

**Comment by jdsjlzx** [comment]
贴一下代码

**Comment by jdsjlzx** [comment]
已修复，请参考！

**Comment by zktzktzkt** [comment]
java.lang.ClassCastException: com.github.jdsjlzx.recyclerview.LRecyclerViewAdapter$ViewHolder cannot be cast to com.example.administrator.animalshopping.fragment.RecentFragment$MyAdapter$MyViewHolder

报这个错误，我是按照标准步骤检查了好几遍都没发现哪写错了，但就是报这个错，麻烦回答一下，在线急等
