### ISSUE TITLE
能解释下为什么在强制刷新后要调用者3条代码吗

### ISSUE THREAD

**Issue by qq294685358** [jdsjlzx/LRecyclerView#50]
能解释下为什么在强制刷新后要调用者3条代码吗  分别是什么用

![qq 20161028143207](https://cloud.githubusercontent.com/assets/15881412/19797157/eef2514a-9d1b-11e6-95bc-d29bb53859e9.png)

**Comment by jdsjlzx** [comment]
mRecyclerView.forceToRefresh();是强制刷新；

下拉刷新完成（无论是否到获取数据）后调用下面代码，更新ＵＩ。
mRecyclerView.refreshComplete();
mLRecyclerViewAdapter.notifyDataSetChanged();
