### ISSUE TITLE
有一个小BUG，麻烦看下

### ISSUE THREAD

**Issue by qq294685358** [jdsjlzx/LRecyclerView#53]
具体表现为这样：做了一个很简单的checkbox的recyclerview，假设有11个checkbox，点击第一个checkbox的时候，第1个checkbox被打上勾了，这是正确的，但是第10个checkbox也被打上勾了。
然后再点击第1个checkbox，勾取消，但是第10个勾也被取消了。

public class TestRecyclerView extends BaseActivity {
    @BindView(R.id.recyclerview)
    LRecyclerView recyclerview;
    private LRecyclerViewAdapter mLRecyclerViewAdapter;
    private TestAdapter mDataAdapter;
    private List<WatchRecordBean> beanList = new ArrayList<>();

    @Override
    public int getContentView() {
        return R.layout.watch_record;
    }

    @Override
    public void initView() {
        initData();
        initRecyclerView();
    }

    /**
     * 初始化recyclerView
     */
    private void initRecyclerView() {
        mDataAdapter = new TestAdapter(this, beanList);
        mLRecyclerViewAdapter = new LRecyclerViewAdapter(mDataAdapter);

        recyclerview.setLayoutManager(new LinearLayoutManager(this));
        recyclerview.setAdapter(mLRecyclerViewAdapter);
        recyclerview.setPullRefreshEnabled(false);
    }

    private void initData() {
        for (int i = 0; i < 11; i++) {
            WatchRecordBean bean = new WatchRecordBean("http://fashioncn.tv/img_test/shizhuang/" + i + ".png", "2016维密时尚内衣秀2016维密时尚内衣秀2016维密时尚内衣秀2016维密时尚内衣秀", "拍摄花絮", "00:07:33", false, false);
            beanList.add(bean);
        }
    }

下面这个是Adapter
public class TestAdapter extends RecyclerView.Adapter<TestAdapter.TestViewHolder> {
    private Context mContext;
    private List<WatchRecordBean> beanList = new ArrayList<>();

    public TestAdapter(Context context, List<WatchRecordBean> list) {
        this.mContext = context;
        this.beanList = list;
    }

    @Override
    public TestViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return new TestViewHolder(LayoutInflater.from(mContext).inflate(R.layout.test, parent, false));
    }

    @Override
    public void onBindViewHolder(TestViewHolder holder, int position) {

    }

    @Override
    public int getItemCount() {
        return beanList.size();
    }

    public class TestViewHolder extends RecyclerView.ViewHolder {
        private CheckBox checkbox;

        public TestViewHolder(View itemView) {
            super(itemView);
            checkbox = (CheckBox) itemView.findViewById(R.id.checkbox);
        }
    }

下面是item布局
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:orientation="vertical">

<CheckBox
    android:id="@+id/checkbox"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:padding="@dimen/dp_size_50"/>
</LinearLayout>

**Comment by qq294685358** [comment]
http://pan.baidu.com/s/1i50mHc5   我录了段简短的视频，麻烦你看看

**Comment by qq294685358** [comment]
经过我测试，把list的size调成比如50，就会变成点击第0个，第9个，第9*2个，第9*3个，第9*4个以此类推，都会被打钩，取消其中任意第9*n个勾，其他的9*n个勾都会被取消。

**Comment by qq294685358** [comment]
同理，radioButton也会出现同样的情况

**Comment by jdsjlzx** [comment]
你好，请用普通的RecyclerView试试！先确认代码逻辑是否有问题！如果是框架的问题，我会及时修正的！

**Comment by qq294685358** [comment]
不是你的问题。。 是recyclerview的复用导致tag混乱  我改了就没问题了
