### ISSUE TITLE
在同一个Activity中的不同fragment里用LRecyclerview出现了bug。。。

### ISSUE THREAD

**Issue by GuinyPendragon** [jdsjlzx/LRecyclerView#54]
我在项目中MainActivity下建立了2个fragment，每个fragment都只有一个LRecyclerView。然而这个两个LRecyclerView似乎会产生冲突。
给的错误信息是： 
java.lang.IllegalArgumentException: called detach on an already detached child ViewHolder

**Comment by jdsjlzx** [comment]
请提供更详细的log

**Comment by jmhjmh** [comment]
请问这个问题解决了嘛！我也遇到了

**Comment by jdsjlzx** [comment]
有用户反应是添加headerview的问题，这里统一说明下：

添加HeaderView、FooterView

//add a HeaderView
mLRecyclerViewAdapter.addHeaderView(new SampleHeader(this));

//add a FooterView
mLRecyclerViewAdapter.addFooterView(new SampleFooter(this));
添加HeaderView还可以使用下面两种方式：

**View header = LayoutInflater.from(this).inflate(R.layout.sample_header,(ViewGroup)findViewById(android.R.id.content), false);**
mLRecyclerViewAdapter.addHeaderView(header);


CommonHeader headerView = new CommonHeader(getActivity(), R.layout.layout_home_header);
mLRecyclerViewAdapter.addHeaderView(headerView);

**Comment by imkobe** [comment]
这个肯定是使用了viewpage的 ，所以你在使用的时候给viewpager一个预加载就可以了  mViewPager.setOffscreenPageLimit(1);

**Comment by Lucidastar** [comment]
CommonFooter commonFooter = new CommonFooter(getActivity(),R.layout.view_footer);
mLRecyclerViewAdapter.addFooterView(commonFooter);
当在下拉刷新时调用（RecyclerViewStateUtils.setFooterViewState(mLRecyclerView, LoadingFooter.State.Normal);）
会出现java.lang.ClassCastException: com.github.jdsjlzx.view.CommonFooter cannot be cast to com.github.jdsjlzx.view.LoadingFooter 在fragment中操作
