### ISSUE TITLE
当时加载的数据不满指定数量时，顶部有一个空item的间隙

### ISSUE THREAD

**Issue by YXY1109** [jdsjlzx/LRecyclerView#55]
假如我加载的数据为5条，设置的一页加载为10条。然后LRecyclerView底部就有一个item的空隙。我使用
RecyclerViewStateUtils.setFooterViewState(VideoActivity.this, recyclerViewCommentList, Constant.LIMIT, LoadingFooter.State.TheEnd, null);这个方法也没效果，请大神看看，能否给点修改的建议。“不好意思啊，标题打错了，是底部”

**Comment by jdsjlzx** [comment]
请参考EndlessLinearLayoutActivity.java类。

**Comment by YXY1109** [comment]
您好，我就是参考EndlessLinearLayoutActivity.java类写的。例如一页加载10条，不瞒10条，底部都会有一个item的高度。是这样，我这里如果是两页，底部就显示正常：显示已全部加载完毕。不瞒一页，就有个空白item
