### ISSUE TITLE
recyclerview布局特别复杂时，下拉会导致recyclerview中item显示错乱

### ISSUE THREAD

**Issue by zuocaijian** [jdsjlzx/LRecyclerView#56]
错乱是指每个item像是自由滚动一样，会发生覆盖，错位等，在低端机上尤其明显
好像下拉时候会不断调用recyclerview的onMeasure和onLayout方法，当recyclerview内容和布局复杂时，会造成性能极大损耗
在AS的monitors里面可以看到出现内存抖动，查看源码发现，在ArrowRefreshHeader类中的onMove方法里会调用getVisibleHeight和setVisibleHeight两个方法，每调用一次都会创建一个LayoutParams对象。
尝试改为使用全局LayoutParams变量后，“错乱”现象有所好转。
不知道两者是不是有直接关系，希望这个项目能再做优化

**Comment by jdsjlzx** [comment]
你好，能不能录个视频看看，其他用户都没有反应过此问题。如有可能，贴出一下你修改的代码，我参考下！

**Comment by zuocaijian** [comment]
@jdsjlzx 抱歉，我重新测试了一下，可能并不是控件的原因，我再看看...
