### ISSUE TITLE
使用这个控件加StaggeredGridLayoutManager不能回顶操作

### ISSUE THREAD

**Issue by aesion** [jdsjlzx/LRecyclerView#58]
各种方法都试过了，就是不能返回到顶部，希望得到回复

**Comment by jdsjlzx** [comment]
StaggeredGridLayoutManager只有这个不能吗？

toTopBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mRecyclerView.scrollToPosition(0);
                toTopBtn.setVisibility(View.GONE);
            }
        });

参考：http://blog.csdn.net/jdsjlzx/article/details/51794220
项目参考：https://github.com/jdsjlzx/Community

**Comment by aesion** [comment]
已解决
