### ISSUE TITLE
LRecyclerView嵌套RecyclerView,导致滑动BUG

### ISSUE THREAD

**Issue by qq294685358** [jdsjlzx/LRecyclerView#59]
具体情况请看我给你分享的视频。代码逻辑是最外层是你的LRecyclerView，然后在里面套一个RecyclerView，在进入新页面时，如果不先滑出第一个RecyclerView，下拉刷新的头部布局会像视频里一样出问题，但是在滑出第一个RecyclerView后再滑回来，下拉刷新头就正常。
http://pan.baidu.com/s/1qXWSUWs

**Comment by jdsjlzx** [comment]
贴一下你的布局文件

**Comment by qq294685358** [comment]
![image](https://cloud.githubusercontent.com/assets/15881412/20298535/7a526a16-ab51-11e6-8dd9-1e1f49befaef.png)
这是LRecyclerView的


![image](https://cloud.githubusercontent.com/assets/15881412/20298567/a064ef76-ab51-11e6-9479-85344a30e60b.png)
这是LRecyclerView里面的RecyclerView


![image](https://cloud.githubusercontent.com/assets/15881412/20298602/c77b26d4-ab51-11e6-80a0-9619acc1c2c0.png)

这是RecyclerView里面的item布局


![image](https://cloud.githubusercontent.com/assets/15881412/20298620/d53ba7a8-ab51-11e6-8664-d0b10b2fa308.png)
这是LrecyclerView里面判断Type来选择new哪一个子Adapter

**Comment by qq294685358** [comment]
你好，你测试过用LrecyclerView嵌套recyclerview吗，有我说的这个BUG吗

**Comment by jdsjlzx** [comment]
我没有这样测试过，如果可以，尽量别这样嵌套，很容易出现滑动冲突的问题！你用RecyclerView嵌套Recyclerview试试，看看有没有出现问题！

另外提供一个思路：你可以控制一下嵌套的RecyclerView，屏蔽他的滑动事件！

**Comment by jdsjlzx** [comment]
参考：http://blog.csdn.net/feiyangbahu1/article/details/52305769，看看能不能解决问题

**Comment by qq294685358** [comment]
其实并不是滑动冲突的问题，我用recyclerview嵌套recyclerview，滑动没有问题没冲突。只有在LRecyclerView嵌套recyclerview的下拉刷新头部才有问题，而只要划出了一页，下拉刷新的头部就正常了。具体问题请看我给你发的视频链接。希望有时间能修改下，谢谢！

**Comment by qq294685358** [comment]
你好，我的问题你测试过了吗？

**Comment by jdsjlzx** [comment]
你好，如果可以，请在demo中修改下，提供给我出问题的demo，我测试下！最近项目赶进度，得抽空才能看这个问题！

**Comment by qq294685358** [comment]
我大概做了个demo，麻烦你看看，里面有2个问题，一个就是我上面所说的下拉刷新头部的问题。另一个是刚进入页面时，LRecyclerView的第一行item会看不到，不是被隐藏了，要往上拉一点才能显示出来。谢谢！    
这是百度云盘的链接    https://pan.baidu.com/s/1kUUv3RT

**Comment by jdsjlzx** [comment]
你好，你看看新增的类：NestRecylcerviewActivity，我试了下，看看还有没有你说的问题，如果有为继续完善下！

**Comment by qq294685358** [comment]
我跑了你最新的工程，试了NestRecylcerviewActivity，我说的下拉刷新头部的问题还是存在。具体表现还是为刚进入页面没有向下滑动，直接下拉刷新，下拉刷新头部出现的过程中，头部会被卡主，而不是很顺畅的滑动出现。而如果一进入页面先往下滑动，再滑回顶部，再去下拉刷新的话，下拉刷新头部就很顺畅。
麻烦有空看下这个问题，谢谢！

**Comment by jdsjlzx** [comment]
可能还是冲突问题，你先自己解决看看！我有空再看看这个问题！

**Comment by qq294685358** [comment]
好的，我尽量自己试试。你有空的话别忘了这个问题就行

**Comment by jdsjlzx** [comment]
@qq294685358 你有解决这个滑动冲突的问题吗？

**Comment by SuperZhouyong** [comment]
@wuzhenhai  这就解决了??    等作者大神分析一下

**Comment by geakw** [comment]
请问这个问题解决了没有，header里面包含recyclerview的问题，我看XRecyclerView这个库也有这个问题

**Comment by geakw** [comment]
`                if (isOnTop() && mPullRefreshEnabled && !mRefreshing) {
                    mRefreshHeader.onMove(deltaY, sumOffSet);
//                    if (mRefreshHeader.getVisibleHeight() > 0) {
//                        return false;
//                    }
                }`
onTouchEvent中将上面的代码注掉就可以滑动，但是下拉刷新的状态不对了，应该是touch事件处理问题

**Comment by geakw** [comment]
`if (isOnTop() && mPullRefreshEnabled && !mRefreshing)
 {
        mRefreshHeader.onMove(deltaY, sumOffSet);
 //     if (mRefreshHeader.getVisibleHeight() > 0) {
 //         return false; 
//     }
 }
onTouchEvent`
中将上面的代码注掉就可以滑动，但是下拉刷新的状态不对了，应该是touch事件处理问题

**Comment by geakw** [comment]
应该是touch事件被拦截掉了，在LReyclerView最外层的父布局上加上android:descendantFocusability=”blocksDescendants”属性就可以了

**Comment by Paul-KK** [comment]
@Override
    public boolean onTouchEvent(MotionEvent ev) {
        if (mLastY == -1) {
            mLastY = ev.getRawY();
        }
        switch (ev.getAction()) {
            case MotionEvent.ACTION_DOWN:
                mLastY = ev.getRawY();
                sumOffSet = 0;
                break;
            case MotionEvent.ACTION_MOVE:
                final float deltaY = (ev.getRawY() - mLastY) / DRAG_RATE;
                mLastY = ev.getRawY();
                sumOffSet += deltaY;
                if (isOnTop() && mPullRefreshEnabled && !mRefreshing && (appbarState == AppBarStateChangeListener.State.EXPANDED)) {
                    System.out.println("deltaY" + deltaY);
                    mRefreshHeader.onMove(deltaY, sumOffSet);
                    if (mRefreshHeader.getVisibleHeight() > 0) {
                      //  return false;
                    }
                }

                break;
            default:
                mLastY = -1; // reset
                if (isOnTop() && mPullRefreshEnabled && !mRefreshing/*&& appbarState == AppBarStateChangeListener.State.EXPANDED*/) {
                    if (mRefreshHeader.onRelease()) {
                        if (mRefreshListener != null) {
                            mRefreshing = true;
                            mFootView.setVisibility(GONE);
                            mRefreshListener.onRefresh();
                        }
                    }
                }
                break;
        }
        return super.onTouchEvent(ev);
    }


如上，不要在move函数中手动拦截或者不拦截touch事件，交给父级（官方recyvleryview里的onTouchEvent）函数自己判断返回值，不能人工干预。至于原因我也不知道。当然 @geakw 的方法也可以，但是需要添加到xml中。这个办法可以一劳永逸。原理都差不多，是Lrecyclerview和它的父控件之间的touch事件关系。

**Comment by jdsjlzx** [comment]
关于LRecyclerView嵌套RecyclerView滑动卡顿的问题

可以参考：https://github.com/jdsjlzx/LRecyclerView/issues/165

**Comment by William353** [comment]
> 我是在LRecyclerView的headView里面带了RecyclerView，也是有下拉刷新冲突。
> 一个比较诡异的解决办法是，在LRecyclerView的同级布局文件下，加入一个空的RecyclerView，下拉刷新就没有冲突了
> ![image](https://cloud.githubusercontent.com/assets/8111421/20788393/9586763c-b7eb-11e6-9ae0-cc72f765f01d.png)
> 原因不明
> 
> 下面是 headview 的布局
> 
> ![image](https://cloud.githubusercontent.com/assets/8111421/20788533/20c06938-b7ec-11e6-863e-8b28a3aa1f47.png)

It works , I use XRecyclerView

**Comment by William353** [comment]
> 我是在LRecyclerView的headView里面带了RecyclerView，也是有下拉刷新冲突。
> 一个比较诡异的解决办法是，在LRecyclerView的同级布局文件下，加入一个空的RecyclerView，下拉刷新就没有冲突了
> ![image](https://cloud.githubusercontent.com/assets/8111421/20788393/9586763c-b7eb-11e6-9ae0-cc72f765f01d.png)
> 原因不明
> 
> 下面是 headview 的布局
> 
> ![image](https://cloud.githubusercontent.com/assets/8111421/20788533/20c06938-b7ec-11e6-863e-8b28a3aa1f47.png)

It works for me , I use XRecyclerView
