### ISSUE TITLE
强制刷新怎么用？

### ISSUE THREAD

**Issue by KKJJ** [jdsjlzx/LRecyclerView#6]
调用强制刷新forceToRefresh之后 为什么一直在刷新

**Comment by jdsjlzx** [comment]
**无论是下拉刷新还是强制刷新，刷新完成后调用下面代码：**

```
mRecyclerView.refreshComplete();
mLRecyclerViewAdapter.notifyDataSetChanged();
```

**Comment by KKJJ** [comment]
直接三行一起调用么？ 还是在onRefresh里面调用上面两句

**Comment by KKJJ** [comment]
加了  直接在强制刷新后面加、在刷新网络请求完成后加、在onRefresh加，三种方式都试了，还是一直刷新。。

**Comment by jdsjlzx** [comment]
贴一下你的代码吧，我看看是不是有冲突了
