### ISSUE TITLE
更新了你最新的    compile 'com.github.jdsjlzx:LRecyclerView:1.2.8'这个版本 studio里的预览显示不出布局了，怎么办

### ISSUE THREAD

**Issue by qq294685358** [jdsjlzx/LRecyclerView#60]
更新了你最新的    compile 'com.github.jdsjlzx:LRecyclerView:1.2.8'这个版本
studio里的预览显示不出布局了，怎么办
![image](https://cloud.githubusercontent.com/assets/15881412/20298400/af731494-ab50-11e6-96ea-49ee4e0e113d.png)

**Comment by jdsjlzx** [comment]
你可以build试试，如果studio显示不出来，也是正常的！

**Comment by qq294685358** [comment]
但是前几个版本是可以的啊，而且不只LRecyclerView显示不出来，我其他的正常的控件布局上也显示不出来了   你那边可以显示吗
