### ISSUE TITLE
没有setRefreshHeader的时候会报错

### ISSUE THREAD

**Issue by lucaszhong** [jdsjlzx/LRecyclerView#61]
log:
java.lang.IllegalArgumentException: itemView may not be null
at android.support.v7.widget.RecyclerView$ViewHolder.<init>(RecyclerView.java:9436)
at com.github.jdsjlzx.recyclerview.LRecyclerViewAdapter$ViewHolder.<init>(LRecyclerViewAdapter.java:328)
atcom.github.jdsjlzx.recyclerview.LRecyclerViewAdapter.onCreateViewHolder(LRecyclerViewAdapter.java:150)...

我是按照示例代码这样写的：
recyclerView.setLayoutManager(new LinearLayoutManager(getContext()));
DataAdapter mDataAdapter = new DataAdapter(getContext());
mDataAdapter.setData(mDataList);
LRecyclerViewAdapter mLRecyclerViewAdapter = new LRecyclerViewAdapter(mDataAdapter);
recyclerView.setAdapter(mLRecyclerViewAdapter);

如果在第四行后面加上 mLRecyclerViewAdapter.setRefreshHeader(new ArrowRefreshHeader(getContext())); 就不会报错
debug发现LRecyclerViewAdapter里执行到
public android.support.v7.widget.RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType)这个方法内部时mRefreshHeader为null 
请大神解惑 如果这是个bug 所有人使用的时候都会这样 但看起来没人提这个Issue 我很困惑

**Comment by jdsjlzx** [comment]
recyclerView用的是LRecyclerView吗？
请参考demo中的LinearLayoutActivity类

**Comment by lucaszhong** [comment]
十分感谢 确实是这个问题 我在布局文件中用的是官方的recyclerview 我是在您以前的一篇关于实现防京东滑动标题栏变色的博客中看到的 那里面用的是recyclerview 我就照着写了
