### ISSUE TITLE
你的这个库和另外一个库XRecyclerView有着相同的问题，如果我在footerView中通过点击实现加载更多的逻辑，加载了大约8个数据之后，最后一个item卡住一半不出来，而且加载更多的布局自动隐藏了。

### ISSUE THREAD

**Issue by XinYiWorld** [jdsjlzx/LRecyclerView#62]
SampleFooter sampleFooter = new SampleFooter(mContext);
        sampleFooter.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //TODO 加载更多
                mDataAdapter.addAll(
                        Arrays.asList(new StudyRecordBean[]{ new StudyRecordBean(String.valueOf(random.nextInt() % 2))
                        })
                );
            }
        });
        //add a FooterView
        mLRecyclerViewAdapter.addFooterView(sampleFooter);

        //禁止刷新
        lrecyclerview.setPullRefreshEnabled(false);

**Comment by jdsjlzx** [comment]
你好，框架就是这样设计的，详见：
[注意事项](https://github.com/jdsjlzx/LRecyclerView#注意事项)

**Comment by jdsjlzx** [comment]
我试了下，没有问题，代码如下：

SampleFooter sampleFooter = new SampleFooter(this);
        sampleFooter.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                //TODO 加载更多
                ArrayList<ItemModel> dataList = new ArrayList<>();
                for (int i = 0; i < 10; i++) {
                    ItemModel itemModel = new ItemModel();
                    itemModel.title = "item" + (i + mDataAdapter.getItemCount());
                    dataList.add(itemModel);
                }
                mDataAdapter.addAll(dataList);
            }
        });
        //add a FooterView
        mLRecyclerViewAdapter.addFooterView(sampleFooter);

        //禁止下拉刷新功能
        mRecyclerView.setPullRefreshEnabled(false);

具体代码参考类：LinearLayoutActivity

**Comment by XinYiWorld** [comment]
可能我的用法有误，我试下看看，多谢了哦！
