### ISSUE TITLE
点击事件建议换成addOnItemTouchListener，itemView直接加监听会和拖动排序冲突好像

### ISSUE THREAD

**Issue by SMask** [jdsjlzx/LRecyclerView#63]
我之前也是itemView直接写点击的，后来
写[RecyclerView拖拽排序](http://mp.weixin.qq.com/s?__biz=MzAxMTI4MTkwNQ==&mid=2650820215&idx=1&sn=7a7da6210f7f0b975674422fa4b159ef&mpshare=1&scene=23&srcid=1104Cl3CS9cubVNxIyO52bdV#rd)的时候，发现排序后点击事件全部失效了，然后就换成了[addOnItemTouchListener方法](http://mp.weixin.qq.com/s?__biz=MzAxMTI4MTkwNQ==&mid=2650820134&idx=1&sn=58103e352e5269159778d35dc36ed207&scene=21#wechat_redirect)来实现点击监听，这个方法的问题我写Demo暂时还没有发现，不知道 你这个要不要考虑兼容一下拖拽的功能 = =

**Comment by jdsjlzx** [comment]
addOnItemTouchListener实现方式有弊端，之前出现过。尽量使用itemView的点击事件比较好！你有好的建议可以留言！

**Comment by SMask** [comment]
啊  ...可以方便说下addOnItemTouchListener出现的问题么= =
然后这个使用ItemTouchHelper.attachToRecyclerView();拖拽排序还是会有问题，position错位和头部崩溃等..
建议兼容一下拖拽吧

**Comment by jdsjlzx** [comment]
拖拽排序已经增加，详见demo！
