### ISSUE TITLE
当列表item个数很少的时候，设置footView未THE_END状态无效

### ISSUE THREAD

**Issue by lbwstco** [jdsjlzx/LRecyclerView#64]
比如列表里有6，7个item的时候

**Comment by jdsjlzx** [comment]
假如一页显示10个，如果不够一页（少于10）的时候就默认不显示底部状态了。如果你实现想显示，可以把pageSize改小点！

**Comment by lbwstco** [comment]
@jdsjlzx pageSize是固定10，并且想显示底部状态

**Comment by lbwstco** [comment]
没找到代码里哪里设置了不够一页的时候默认不显示，能否告知下

**Comment by jdsjlzx** [comment]
详见RecyclerViewStateUtils类，[RecyclerViewStateUtils](https://github.com/jdsjlzx/LRecyclerView/blob/master/LRecyclerview_library/src/main/java/com/github/jdsjlzx/util/RecyclerViewStateUtils.java)第41行

**Comment by jdsjlzx** [comment]
compile 'com.github.jdsjlzx:LRecyclerView:1.2.9' 试试最新版本！

**Comment by jdsjlzx** [comment]
最新版本验证！
