### ISSUE TITLE
使用LRecyclerView时，getSpanSize失效

### ISSUE THREAD

**Issue by xie123** [jdsjlzx/LRecyclerView#66]
在用GridLayoutManager的布局样式的时候。getSpanSize不会执行

**Comment by xie123** [comment]
gridlayoutmanager.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                return shopseaarchreasultAdapter.getData().get(position).state ? 1 : 2;
            }
        });

     return shopseaarchreasultAdapter.getData().get(position).state ? 1 : 2;这句话不会执行

**Comment by jdsjlzx** [comment]
参考：EndlessGridLayoutActivity类中：
//setLayoutManager
        GridLayoutManager manager = new GridLayoutManager(this, 2);
        manager.setSpanSizeLookup(new HeaderSpanSizeLookup((LRecyclerViewAdapter) mRecyclerView.getAdapter(), manager.getSpanCount()));
        mRecyclerView.setLayoutManager(manager);

**Comment by jdsjlzx** [comment]
你好，已经解决此Bug，代码如下：

`mLRecyclerViewAdapter.setSpanSizeLookup(new LRecyclerViewAdapter.SpanSizeLookup() {
            @Override
            public int getSpanSize(GridLayoutManager gridLayoutManager, int position) {
                if (position == 3) {
                    return gridLayoutManager.getSpanCount();
                } else if (position == 7 ) {
                    return gridLayoutManager.getSpanCount() - 1;
                } else {
                    return 1;
                }

            }
        });`

参考类：MulItemGridLayoutActivity
