### ISSUE TITLE
请问下关于底部多空白区域问题

### ISSUE THREAD

**Issue by danniu1314** [jdsjlzx/LRecyclerView#67]
我没有做上拉加载，只做了下拉刷新，出现了底部多了一条白带。就是end的空白区域。这个如何取消这块白色的区域。为何我在网上拿1.2.8的和你这里面的代码不一样。

**Comment by jdsjlzx** [comment]
上个效果图吧！

**Comment by wuzhenhai** [comment]
我也出现这个问题，不过暂时的解决办法是，加了个高度为1的footView

**Comment by danniu1314** [comment]
![image](https://cloud.githubusercontent.com/assets/15703913/20779666/daf2bdd8-b7b0-11e6-99f1-fca7938fa254.png)

下部都有一块白色的区域  我没有添加上拉加载   只做了下拉刷新

**Comment by danniu1314** [comment]
![r_d yl61hfrvn he s](https://cloud.githubusercontent.com/assets/15703913/20779739/6cd5d276-b7b1-11e6-8752-6215209ecb33.png)
红色框内就是   滑动到最底部有一块这个空白的   另外一个页面也有  只做了下拉刷新  没做上拉加载这块

**Comment by yixi195** [comment]
我也遇见了。 底部会多出空白的 。 
![default](https://cloud.githubusercontent.com/assets/16281812/20779801/c9ef3588-b7b1-11e6-8b4f-3126a96aed8a.png)

**Comment by jdsjlzx** [comment]
我看到大家的反馈了，我重点关注下！多谢大家的反馈！

**Comment by jdsjlzx** [comment]
compile 'com.github.jdsjlzx:LRecyclerView:1.2.9' 此版本解决！

**Comment by danniu1314** [comment]
非常感谢。
