### ISSUE TITLE
addHeaderView出现bug

### ISSUE THREAD

**Issue by qq294685358** [jdsjlzx/LRecyclerView#69]
我的逻辑是这样的：进入页面首先刷新数据，并且   
 View hearderViewLayout = LayoutInflater.from(this).inflate(R.layout.fashion_formational_header, (ViewGroup) findViewById(android.R.id.content), false);
mLRecyclerViewAdapter.addHeaderView(hearderViewLayout);
然后下拉刷新的时候，重新获取到了headerView的数据，再次运行上面那2行代码。
但是就出问题了：
![image](https://cloud.githubusercontent.com/assets/15881412/20747651/db23a78a-b725-11e6-98b8-18ca9de8cb2e.png)
请问这是怎么回事？

**Comment by qq294685358** [comment]
找到问题了，
 mLRecyclerViewAdapter.removeHeaderView(hearderViewLayout);
 RecyclerViewUtils.removeHeaderView(recyclerview);
关键在于这两个代码的区别，如果用第一行代码在下拉刷新后先移除头部再添加头部，就会报错。
如果用第二行代码在下拉刷新后先移除头部再添加头部，就正常。

整个添加头部的代码是这样的：
  hearderViewLayout = LayoutInflater.from(this).inflate(R.layout.fashion_formational_header, (ViewGroup) findViewById(android.R.id.content), false);
   RecyclerViewUtils.removeHeaderView(recyclerview);
  mLRecyclerViewAdapter.addHeaderView(hearderViewLayout);

希望你有空能看看修改下bug

**Comment by jdsjlzx** [comment]
RecyclerViewUtils.removeHeaderView(recyclerview);

这里怎么把recyclerview传进去了？不是你的heaheaderview吗

**Comment by jdsjlzx** [comment]
如果你下拉刷新的时候需要同时更新headview，不必调用RecyclerViewUtils.removeHeaderView(view)这个方法，直接更新headview即可！

**Comment by qq294685358** [comment]
![image](https://cloud.githubusercontent.com/assets/15881412/20780307/ea5ec088-b7b4-11e6-931c-cdd3095fc872.png)
RecyclerViewUtils.removeHeaderView(recyclerview);
这个方法你自己写的传recyclerview进去的啊

**Comment by qq294685358** [comment]
![image](https://cloud.githubusercontent.com/assets/15881412/20780410/a7bff246-b7b5-11e6-8aa0-6e46ce0a3e8c.png)
我在下拉刷新获取到新数据后，重新运行这个方法，然后就报错了  报的错就是第一张图那个

**Comment by jdsjlzx** [comment]
请使用mLRecyclerViewAdapter.removeHeaderView(view);试试！

你下拉刷新的时候，为什么要remove这个headerview呢？

**Comment by jdsjlzx** [comment]
新版本解决你说的问题，请继续关注

**Comment by jdsjlzx** [comment]
compile 'com.github.jdsjlzx:LRecyclerView:1.2.9' 此版本解决，请验证！

**Comment by qq294685358** [comment]
好的 我试试
