### ISSUE TITLE
关于侧滑点击事件的问题

### ISSUE THREAD

**Issue by bradXie1992** [jdsjlzx/LRecyclerView#70]
当我开启右划出菜单时，在item范围内，只要我往右边滑动（划出菜单关闭），就会触发点击事件。
大神能不能帮忙看下是什么问题啊？

**Comment by jdsjlzx** [comment]
我会重点关注下

**Comment by bradXie1992** [comment]
![6s 3cgj9 3 o i c mdh7](https://cloud.githubusercontent.com/assets/20900353/20784024/a9d8a498-b7d2-11e6-94d0-5713de02e588.jpg)

我再SwipeMenuView里面加了这段代码，好像可以，但是不知道会不会出现其他BUG

**Comment by jdsjlzx** [comment]
我验证下！

**Comment by hblolj** [comment]
@jdsjlzx 现在有其他方法可以避免##侧滑关闭## 触发点击事件吗？

**Comment by jdsjlzx** [comment]
@bradXie1992 截图中的gap变量是什么含义？

**Comment by bradXie1992** [comment]
![default](https://cloud.githubusercontent.com/assets/20900353/20785861/759da560-b7dd-11e6-8d92-12840b4b1912.png)
我把这个提成全局变量了。

**Comment by jdsjlzx** [comment]
我再验证下，今天会发个版本，不过不影响这个功能！侧滑的功能主要是在demo中实现的！
