### ISSUE TITLE
如果addHeaderView第二个头布局，其中加入的是一个RecyclerView，会崩溃。

### ISSUE THREAD

**Issue by danniu1314** [jdsjlzx/LRecyclerView#72]
![image](https://cloud.githubusercontent.com/assets/15703913/20842495/ae84ede6-b8f2-11e6-8085-9faf094095e0.png)
但是如果第一个加就不会出现这个问题。没找到这个的原因

**Comment by jdsjlzx** [comment]
参考：
`        
//add a HeaderView
View header = LayoutInflater.from(this).inflate(R.layout.sample_header,(ViewGroup)findViewById(android.R.id.content), false);
`
`
        mLRecyclerViewAdapter.addHeaderView(header);
        mLRecyclerViewAdapter.addHeaderView(new SampleHeader(this));`


详见：LinearLayoutActivity类

**Comment by jdsjlzx** [comment]
下面的用法是会报错的：
`View header = LayoutInflater.from(this).inflate(R.layout.sample_header,(ViewGroup)findViewById(android.R.id.content), false); mLRecyclerViewAdapter.addHeaderView(header);
mLRecyclerViewAdapter.addHeaderView(header);`

不要连续添加同一个view为header！
