### ISSUE TITLE
在Fragment中进行操作

### ISSUE THREAD

**Issue by Lucidastar** [jdsjlzx/LRecyclerView#73]
CommonFooter commonFooter = new CommonFooter(getActivity(),R.layout.view_footer);
mLRecyclerViewAdapter.addFooterView(commonFooter);
当在下拉刷新时调用（RecyclerViewStateUtils.setFooterViewState(mLRecyclerView, LoadingFooter.State.Normal);）
会出现java.lang.ClassCastException: com.github.jdsjlzx.view.CommonFooter cannot be cast to com.github.jdsjlzx.view.LoadingFooter 在fragment中操作

**Comment by jdsjlzx** [comment]
详见https://github.com/jdsjlzx/LRecyclerView#注意事项
