### ISSUE TITLE
下拉也会触发加载更多

### ISSUE THREAD

**Issue by DeveloperXu** [jdsjlzx/LRecyclerView#76]
先拉到底部，然后稍微上拉一点，保持footview仍然显露，这时还会触发loadmore()
可以再定义一个字段记录上拉还是下拉，在onScrolled()中赋值
然后在调用loadmore()的地方加一个判断，就能解决

**Comment by jdsjlzx** [comment]
你好，你走demo中能复现这个问题吗？

**Comment by DeveloperXu** [comment]
demo中没有出现，但那是你代码控制的，但实际业务并不会按照你那种写法写
我改了你demo中的代码，然后就出现了，我看了你的源码loadmore()是在onScrollStateChanged中调用的，虽然在onScrolled中有过对方向判断的代码，但那是做别的判断
对了是LuRecyclerView

**Comment by jdsjlzx** [comment]
把能复现问题的demo代码贴一下吧！我分析下！另外贴一下你的解决方案，我验证下！

**Comment by DeveloperXu** [comment]
怎么给你回邮件呀

**Comment by jdsjlzx** [comment]
jdsjlzx@qq.com，如果能有截图附带上最好！

**Comment by DeveloperXu** [comment]
给你发的代码，写了注释说明

**Comment by jdsjlzx** [comment]
新版本解决此问题！

**Comment by jdsjlzx** [comment]
compile 'com.github.jdsjlzx:LRecyclerView:1.3.0'

新版本中你验证下你的问题！
