### ISSUE TITLE
Demo里面一个小BUG

### ISSUE THREAD

**Issue by Biswangluo** [jdsjlzx/LRecyclerView#77]
![screenshot_20161213-140905](https://cloud.githubusercontent.com/assets/2362450/21129623/e0ea58ea-c13d-11e6-82fd-92fabfe7f4ff.png)

项目中套用了这个东西， 发现Birds栏目的Pigeon点击事件位置错误，会显示上一个，但其他所有的条目都正常，检查发现位置减多了一个，很奇怪的问题，找了半天也没发现问题在哪里。

**Comment by jdsjlzx** [comment]
你找到问题了反馈下吧，这个demo只是为了提供一个思路！
