### ISSUE TITLE
有一个bug在demo里

### ISSUE THREAD

**Issue by chain911** [jdsjlzx/LRecyclerView#80]
SwipDeleteActivity这个类，正常置顶是点击置顶后侧滑菜单栏收进去 相应条目也置顶了 但有时候侧滑菜单栏收不回去 能一直点击置顶 可是有的item的侧滑菜单项里面并没有“置顶”按钮；
另外有个建议就是希望可以加上拖拽排序功能，博主的Demo里面的侧滑菜单不太灵活，有另一个RecycleView除了下拉和上拉不完美其余的都不错，希望博主可以结合这个https://github.com/yanzhenjie/SwipeRecyclerView能够做出来一个既可以下拉刷新又能上拉加载还能侧滑，还可以拖拽排序的，期待

**Comment by jdsjlzx** [comment]
参考：ListDragMenuActivity类！还在优化中，请提建议！

**Comment by jdsjlzx** [comment]
RecycleView下拉和上拉不完美，你有什么建议呢？

**Comment by chain911** [comment]
我意思你这个下拉和上拉很实用 只是你这个的侧滑用起来就不太灵活 并且没有拖拽排序 而https://github.com/yanzhenjie/SwipeRecyclerView侧滑 拖拽排序都有 但是他的下拉上拉不好 要是能和你的这个结合一起 那就太完美了

**Comment by jdsjlzx** [comment]
https://github.com/yanzhenjie/SwipeRecyclerView 这个我曾经试过，导致了RecyclerView滑动卡顿的问题，不得已去掉了。我想尽量在adapter里面做到这个拖拽功能，而不跟RecyclerView耦合太多。

详见：https://github.com/jdsjlzx/LRecyclerView/issues/12
