### ISSUE TITLE
请问怎么改变下拉刷新头部文字的颜色

### ISSUE THREAD

**Issue by qq294685358** [jdsjlzx/LRecyclerView#81]
请问怎么改变下拉刷新头部文字的颜色，也就是下拉刷新头部的  释放立即刷新   这几个文字的颜色

**Comment by jdsjlzx** [comment]
暂时没有对应的api，你可以重写这个listview_header.xml布局文件（拷贝listview_header.xml到你的本地app）即可。

链接地址：https://github.com/jdsjlzx/LRecyclerView/blob/master/LRecyclerview_library/src/main/res/layout/listview_header.xml

注意：不要修改控件的id，字体颜色、文本内容你都可以修改！

**Comment by SMask** [comment]
我找到一个很简单的方法...

    <style name="AppTheme" parent="AppBaseTheme">
        <item name="android:windowNoTitle">true</item>
        
        
        <item name="android:windowBackground">@color/main_bg</item>
        <item name="android:textSize">@dimen/main_font_content</item>
        <item name="android:textColor">@color/main_font</item>
    </style>

清单文件 application 的主题 style里面 加上 textSize 和 textColor 然后 换上你想要的就可以
同时，APP里面没有自定义TextView的都会使用这个大小和字体

**Comment by jdsjlzx** [comment]
nice

**Comment by SMask** [comment]
同时 上拉加载  如果不想自定义  改颜色的话 
在 项目的 color.xml 里面
<color name="colorAccent">@color/main_font</color>
这个 colorAccent 就是上拉的 进度条 和 字体颜色

**Comment by jdsjlzx** [comment]
下面三个颜色的定义会影响整个app的主题颜色！
`<color name="colorPrimary">#fff8c138</color>
 <color name="colorPrimaryDark">#FFf5a623</color>
 <color name="colorAccent">#fff8c138</color>
`

**Comment by SMask** [comment]
嗯呐 对的 但是我的项目里面 这三个颜色全没用到 - -
所以 就通过这个取巧 改了上拉加载的颜色
 = =
