### ISSUE TITLE
大神,为什么我addheardView总是失败,一片空白

### ISSUE THREAD

**Issue by gdjsdk** [jdsjlzx/LRecyclerView#82]
adapter = new HomeNewsAdapter(mContext, datasEvents);
         LRecyclerViewAdapter  mLRcVAdapter=new LRecyclerViewAdapter(adapter);
        homeViewPagerHeard = new HomeViewPagerHeard(mContext, null,R.layout.view_home_viewpager_heard);
        mLRcVAdapter.addHeaderView(homeViewPagerHeard);
        mLRcVAdapter.addHeaderView(homeButton);
        lv_news.setAdapter(mLRcVAdapter);

**Comment by jdsjlzx** [comment]
参考：https://github.com/jdsjlzx/LRecyclerView#添加headerviewfooterview

你可以详见demo中的例子！
