### ISSUE TITLE
大神，请问这个数据越界异常如何解决

### ISSUE THREAD

**Issue by sh1018727638** [jdsjlzx/LRecyclerView#83]
![image](https://cloud.githubusercontent.com/assets/18133575/21344463/dfab8a0a-c6d6-11e6-8360-881968125787.png)

我是在SwipeRefrshLayout下拉刷新之后立刻上滑到底部加载时，就产生了这个问题

**Comment by jdsjlzx** [comment]
代码截图看看

**Comment by sh1018727638** [comment]
截图截不全，大神，我已经发您邮箱了，您有空的话看看吧，麻烦指点一下，邮件标题就是这个Issue的

**Comment by jdsjlzx** [comment]
代码我看不到问题，请打印log，看看索引值是多少！

**Comment by sh1018727638** [comment]
这个是索引，情况是当我下拉刷新动作未完成时，往上滑，就会出现这个错误
![image](https://cloud.githubusercontent.com/assets/18133575/21445715/32e64aa8-c8f7-11e6-93d7-b2a852e2580a.png)
这个情况是，当我下拉刷新动作未完成时，立刻快速滑动到底部，就会出现这个错误
![image](https://cloud.githubusercontent.com/assets/18133575/21445718/457ca5d6-c8f7-11e6-9634-c004b4948230.png)

**Comment by jdsjlzx** [comment]
你好，应该是用法有误导致的，请参考：SwipeRefreshLayoutActivity类。如果你还有问题，可以在demo中修改试试看看能不能复现你的问题！

**Comment by sh1018727638** [comment]
感谢，确实是我用法的问题
