### ISSUE TITLE
加入侧滑删除后，滑动列表数据错乱问题

### ISSUE THREAD

**Issue by zktzktzkt** [jdsjlzx/LRecyclerView#85]
购物车用到了侧滑删除：购物车商品列表总数有15个，第1个商品的默认数量是1个，我加到了3个；我滑动到最后一条，然后再滑到第一条，结果第一条的数量由3又变成了1

**Comment by jdsjlzx** [comment]
你好，这个是数据错乱的问题应该不是框架导致的问题，请你再排查下！
