### ISSUE TITLE
compile 'com.github.jdsjlzx:LRecyclerView:1.3.0'这种方式依赖的时候怎么去修改footview

### ISSUE THREAD

**Issue by sunkeding** [jdsjlzx/LRecyclerView#87]
正在加载中的文字颜色需要改变，然后加载的图标也需要改变，就是不清楚不导入module的情况下怎么修改方便些

**Comment by jdsjlzx** [comment]
将libray中的layout/layout_recyclerview_list_footer_loading.xml 拷贝此文件到你的工程修改样式和颜色即可！
注意：不用修改控件的ID。
