### ISSUE TITLE
Sticky Header能加入下拉刷新加载更多么

### ISSUE THREAD

**Issue by handy0529** [jdsjlzx/LRecyclerView#89]
你好，Sticky Header能加入下拉刷新加载更多么，试了下下拉刷新在header下面显示，有什么方法解决吗？

**Comment by handy0529** [comment]
![s61227-19002228](https://cloud.githubusercontent.com/assets/4454883/21498419/35ed1466-cc67-11e6-9115-19278aa66518.jpg)

**Comment by jdsjlzx** [comment]
暂时没有好的方法！

**Comment by jdsjlzx** [comment]
如果没有问题，我先关闭该issue，如有问题你可以重新提issue！
