### ISSUE TITLE
下拉刷新样式问题

### ISSUE THREAD

**Issue by FrankZhang007** [jdsjlzx/LRecyclerView#9]
setRefreshProgressStyle 时候，progress 的颜色能换吗

如何自定义 下拉的样式，没有发现对外设置 view 的方法

**Comment by jdsjlzx** [comment]
设置下拉刷新样式：

mRecyclerView.setRefreshProgressStyle(ProgressStyle.BallSpinFadeLoader); //设置下拉刷新Progress的样式
mRecyclerView.setArrowImageView(R.drawable.iconfont_downgrey);  //设置下拉刷新箭头
AVLoadingIndicatorView库有多少效果，LRecyclerView就支持多少下拉刷新效果，当然你也可以自定义下拉刷新效果。

progress的颜色与你的主题设置有关，也就是<item name="colorAccent">@color/colorAccent</item>的定义。

自定义下拉效果可以参考源码实现，后续会出demo实现！

**Comment by KKJJ** [comment]
加载更多样式能自定义吗

**Comment by axkza** [comment]
自定义头部刷新是参考ArrowRefreshHeader吗？然后修改后还得替换LRecyclerViewAdapte中的ArrowRefreshHeader是吧？

**Comment by jdsjlzx** [comment]
替换也可以，你也可以在本地app自定义，放在本地！具体效果我没有试过，如果你自定义好了，没有问题，可以发给我，我可以作为demo放到源码里面，帮助更多的人！

**Comment by axkza** [comment]
我最后只是修改了ArrowRefreshHeader，本地自定义还是不懂。

我发现下拉阻力有点大，我就在Lrecyclerview的case MotionEvent.ACTION_MOVE:方法里，修改成1.5倍感觉下拉会比较顺滑
mRefreshHeader.onMove((int)(deltaY / DRAG_RATE*1.5));

**Comment by jdsjlzx** [comment]
我试一下！

**Comment by jdsjlzx** [comment]
DRAG_RATE改为2了，到时候看看反馈效果！
