### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by XinYiWorld** [jdsjlzx/LRecyclerView#90]
我自己了写了个多用途的adapter，加载更多里采用了AVLoadingIndicatorView，为什么第一次出现动画正常，但是之后AVLoadingIndicatorView就卡住了呢？

**Comment by jdsjlzx** [comment]
你好，这个问题我也遇到了，只能每次动态添加AVLoadingIndicatorView动画才正常，不能复用！具体原因还得问问AVLoadingIndicatorView的作者！

**Comment by XinYiWorld** [comment]
多谢大神！

**Comment by XinYiWorld** [comment]
另外大神，我再请问个问题啊，我把项目上传到了jfrog bintray,为什么Linked to 那个选项没有“Add to Jcenter"，网上有人说在 [https://bintray.com/bintray/jcenter](url) 这里include my package，为什么找不到我的项目啊？

**Comment by jdsjlzx** [comment]
具体你百度下，jcenter这个方式我没有用过，你可以用jitpack，参考：http://blog.csdn.net/jdsjlzx/article/details/51981993。

**Comment by XinYiWorld** [comment]
我突然发现那个AVLoadingIndicatorView动画为什么卡了的问题，如果动态设置了AVLoadingIndicatorView的动画样式，导致mIndicatorController重新new了，需要重新调用一下applyAnimation()方法，否则动画集就是null，就不会start动画了。
