### ISSUE TITLE
Android 4.4.4下addItemDecoration出现了如下图得情况，请问作者这是怎么回事呢

### ISSUE THREAD

**Issue by love-311** [jdsjlzx/LRecyclerView#91]
![image](https://cloud.githubusercontent.com/assets/19263806/21517229/3885d076-cd18-11e6-9e25-7fd9f9e048dd.png)

**Comment by love-311** [comment]
我发现这个非常奇怪，当点击刷新的位置在item上就不会有这么多线，但是如果是在item外点击的刷新就会出现上面的情况。。

**Comment by love-311** [comment]
但是我还是比较疑惑这个应该也是一个bug吧？

**Comment by jdsjlzx** [comment]
你用普通的RecylerView验证下试试，LRecyclerView对ItemDecoration支持不够好（由于Header和Footer的原因）

**Comment by love-311** [comment]
我昨天就在想试试是不是RecylerView本身源码的问题，就是自己还没有去尝试。。(*^__^*) 嘻嘻……感谢大神，经常从你的文章中学到很多。。

**Comment by jdsjlzx** [comment]
有好的建议要反馈啊

**Comment by love-311** [comment]
好滴。。

**Comment by jdsjlzx** [comment]
经过优化，LRecyclerView 支持了ItemDecoration，赶快试试吧！

https://github.com/jdsjlzx/LRecyclerView#关于添加分割线

**Comment by love-311** [comment]
今天早上来实践了一下，在4.4的系统上面跟之前是一样的。。
![image](https://cloud.githubusercontent.com/assets/19263806/21583959/eefc9ea0-d0d0-11e6-9793-b6f3b2d95ee8.png)
