### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by Fisherman91** [jdsjlzx/LRecyclerView#92]
![image](https://cloud.githubusercontent.com/assets/17759213/21518911/7b43f76a-cd24-11e6-97ec-93829908cea5.png)
![image](https://cloud.githubusercontent.com/assets/17759213/21519160/0651b350-cd26-11e6-8a58-2d99f1a2393e.png)
是否考虑优化这2个地方？：
1.更新FooterState时传Fragment参数，并且判断Fragment是否已无效，实际开发中为了复用性 大部分UI都是在Fragment中实现的吧？
2.AVLoadingIndicatorView已经更新了显示/隐藏的方式，是否应该更新一下，以免内存泄露。

**Comment by jdsjlzx** [comment]
1.关于第一个，我还是倾向于用Activity，毕竟这个更通用些，一旦改为了Fragment，万一有人用Activity呢？
2.关于AVLoadingIndicatorView我会尽快更新

感谢你的反馈！

**Comment by Fisherman91** [comment]
我不是说改掉，而是搞个重载方法，不就既支持Activity又支持Fragment了么。

**Comment by jdsjlzx** [comment]
Good，已采纳，下个版本1.3.2中改进！

**Comment by Fisherman91** [comment]
作者已经答应修改
