### ISSUE TITLE
升级后出现的问题

### ISSUE THREAD

**Issue by zktzktzkt** [jdsjlzx/LRecyclerView#94]
FATAL EXCEPTION: main
                                                                                        
java.lang.IllegalStateException:Observercom.github.jdsjlzx.recyclerview.LRecyclerView$DataObserver@437b9bf0 was not registered.
                                                                                            
at android.database.Observable.unregisterObserver(Observable.java:69)
                                                                                            
at android.support.v7.widget.RecyclerView$Adapter.unregisterAdapterDataObserver(RecyclerView.java:6294)
                                                                                            
at com.github.jdsjlzx.recyclerview.LRecyclerView.setAdapter(LRecyclerView.java:133)

大神，我从1.2.9升级到1.3.1，就报这个错误

**Comment by jdsjlzx** [comment]
请参考最新的demo，另外最近在优化代码，如果不着急，请先不要升级，等1.3.2版本发布！可以先关注demo！

**Comment by jdsjlzx** [comment]
问题解决了吗
