### ISSUE TITLE
拉到底部加载更多的view没有显示

### ISSUE THREAD

**Issue by YukiExcalibur** [jdsjlzx/LRecyclerView#95]
上啦到最低部的时候就不能拉了，但是底部的加载更多的view没有显示出来，而且不能加载更多，设置了setLoadMoreEnabled（true）才拉到底部加载数据，但还是没有加载更多的view，代码如下
  mLRecyclerViewAdapter = new LRecyclerViewAdapter(mAdapter);    mLRecyclerViewAdapter.addFooterView(LayoutInflater.from(mContext).inflate(com.github.jdsjlzx.R.layout.layout_recyclerview_list_footer,null));
        mListView.setRefreshProgressStyle(ProgressStyle.BallSpinFadeLoader);
        mListView.setAdapter(mLRecyclerViewAdapter);
        mListView.setLoadMoreEnabled(true);

**Comment by jdsjlzx** [comment]
下面代码不用写：
mLRecyclerViewAdapter.addFooterView(LayoutInflater.from(mContext).inflate(com.github.jdsjlzx.R.layout.layout_recyclerview_list_footer,null));

具体用法请详见demo！
