### ISSUE TITLE
怎么修改加载刷新时圈的颜色和字体颜色

### ISSUE THREAD

**Issue by YukiExcalibur** [jdsjlzx/LRecyclerView#96]
我在libray改了footer的颜色，但是还是粉色的
![image](https://cloud.githubusercontent.com/assets/17423462/21634664/cbeb42da-d293-11e6-91ee-ea5f818d5367.png)

**Comment by jdsjlzx** [comment]
更改你本地app项目里面的<color name="colorAccent">#FF4081</color> 这个值，本地的会覆盖libray中是颜色！

**Comment by XuanJiAndroid** [comment]
请问怎么更改底部的加载完成字样？@jdsjlzx
