### ISSUE TITLE
怎么更改底部的加载完成字样？

### ISSUE THREAD

**Issue by XuanJiAndroid** [jdsjlzx/LRecyclerView#98]
@jdsjlzx 请问这个底部样式怎么改？如改文字和颜色

![image](https://cloud.githubusercontent.com/assets/21168212/21640981/b4be2558-d2b3-11e6-9c2f-32862f74623a.png)

**Comment by jdsjlzx** [comment]
参考：EndlessLinearLayoutActivity类：

`mRecyclerView.setFootViewHint("拼命加载中","已经全部为你呈现了","网络不给力啊，点击再试一次吧");
`

compile 'com.github.jdsjlzx:LRecyclerView:1.3.2'

**Comment by jdsjlzx** [comment]
如果以上不能满足你的需求，可以如下操作：
拷贝libray中的layout_recyclerview_list_footer_loading.xml文件到本地，修改文字和颜色即可！1

**Comment by jdsjlzx** [comment]
下个版本将提供相应的api，请稍等！

**Comment by jdsjlzx** [comment]
详见：https://github.com/jdsjlzx/LRecyclerView/blob/master/README.md#设置下拉刷新header和footer文字内容和颜色
